---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(MASS)
})
```



```{r}
show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[4],pal_uchicago("default")(9)[5],pal_uchicago("default")(9)[9])
```


#Load Data
```{r}
ms1 <- read.csv("../../raw/MS1/MS1_250217_neutral_segmented_both_means.csv")
ms1$Diff <- "MS1"
ms2 <- read.csv("../../raw/MS2/MS2_250206_neutral_segmented_both_means.csv")
ms2$Diff <- "MS2"
ms3 <- read.csv("../../raw/MS3/MS3_250207_neutral_segmented_both_means.csv")
ms3$Diff <- "MS3"

e <- rbind(ms1,ms2,ms3)
e$sample <- gsub("control","pLNA-Ctrl",e$sample)
e$sample <- gsub("1229","pLNA-1229",e$sample)
e$sample <- factor(e$sample,levels = c("pLNA-Ctrl","pLNA-1229","TSB"))
```

```{r}
replacement <- c(MS1 = "r1", MS2 = "r2", MS3 = "r3")
e$Diff <- replacement[as.character(e$Diff)]
e$Diff <- factor(e$Diff,levels = c("r1","r2","r3"))
```


```{r}
e$ratio <- e$acidic_intensity / (e$acidic_intensity + e$neutral_intensity)
e <- e[e$area > 10,]
```

```{r}
#exclude the TSB condition
e <- e[e$sample != "TSB",]
e$sample <- droplevels(e$sample)
```

```{r}
saveRDS(e,"../Data/automated.rds")
```


