---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(MASS)
})
```



```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```


#Load Data
```{r}
e <- readRDS("../DataPrep/IndMito.rds")
e$Condition <- factor(e$Condition,levels = c("pLNA-Ctrl","pLNA-1229"))
e$Differentiation <- tolower(e$Differentiation)
```

```{r}
#exclude the wrongly processed ones
#would lead to the same results, therefore leave in
#e <- e[!grepl("^230511_michael_M1_control_2023_05_11_[0-9_]*_SIM²\\.czi$", e$file), ]
```


##################
##################
## All Mitos
## Aggregate by image
```{r}
#area
ag_area <- aggregate(e$Mito_Area_um,e[,c("Differentiation","Condition","Day","Image")], FUN=mean)

mod_s1a <- lm(x ~ Condition + Differentiation,data = ag_area[ag_area$Day == "Day 29",])
s1a <- emmeans(mod_s1a, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s1b <- lm(x ~ Condition + Differentiation,data = ag_area[ag_area$Day == "Day 36",])
s1b <- emmeans(mod_s1b, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s1 <- lm(x ~ Condition*Day + Differentiation*Day,data = ag_area)
s1 <- emmeans(mod_s1, trt.vs.ctrl ~ Condition | Day , ref="pLNA-Ctrl")


s1a_df <- as.data.frame(s1a$contrasts)
s1a_df$group1 <- "pLNA-Ctrl"
s1a_df$group2 <- s1a_df$contrast
s1a_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s1a_df$group2)
s1a_df$group2 <- gsub("\\(", "",s1a_df$group2)
s1a_df <- add_significance(s1a_df,p.col = "p.value")
s1a_df$p.value.signif <- round(s1a_df$p.value,3)
s1a_df$Day <- "Day 29"

s1b_df <- as.data.frame(s1b$contrasts)
s1b_df$group1 <- "pLNA-Ctrl"
s1b_df$group2 <- s1b_df$contrast
s1b_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s1b_df$group2)
s1b_df$group2 <- gsub("\\(", "",s1b_df$group2)
s1b_df <- add_significance(s1b_df,p.col = "p.value")
s1b_df$Day <- "Day 36"

s1_df <- rbind(s1a_df,s1b_df)


y_pos <- c()
for(i in s1_df$Day) {
  ll <- max(ag_area[ag_area$Day == i,"x"])
  y_pos <- c(y_pos,ll)
}

s1_df$y_pos <- y_pos*1.05

p1 <- ggplot(ag_area,aes(x = Condition, y = x)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  facet_wrap(~Day) +
  coord_cartesian(ylim = c(0,NA)) +
  ylab("Mitochondrial Area in µm²") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  coord_cartesian(ylim = c(0,0.3)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figure_Output/SIM_MitoArea.png",p1, width = 7,height = 4.75, bg = "white")
```



```{r}
p1b <- ggplot(ag_area[ag_area$Day == "Day 36",],aes(x = Condition, y = x)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df[s1_df$Day == "Day 36",],
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  coord_cartesian(ylim = c(0,NA)) +
  facet_wrap(~Day) +
  ylab("Mitochondrial Area in µm²") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  coord_cartesian(ylim = c(0,0.3)) +
  labs(color = "Diff") +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figure_Output/SIM_MitoArea_Day36.png",p1b, width = 4.25,height = 4.75, bg = "white")
```









```{r}
#length
ag_length <- aggregate(e$Length,e[,c("Differentiation","Condition","Day","Image")], FUN=mean)


mod_s2a <- lm(x ~ Condition + Differentiation,data = ag_length[ag_length$Day == "Day 29",])
s2a <- emmeans(mod_s2a, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s2b <- lm(x ~ Condition + Differentiation,data = ag_length[ag_length$Day == "Day 36",])
s2b <- emmeans(mod_s2b, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s2 <- lm(x ~ Condition*Day + Differentiation*Day,data = ag_length)
s2 <- emmeans(mod_s2, trt.vs.ctrl ~ Condition | Day , ref="pLNA-Ctrl")

s2a_df <- as.data.frame(s2a$contrasts)
s2a_df$group1 <- "pLNA-Ctrl"
s2a_df$group2 <- s2a_df$contrast
s2a_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s2a_df$group2)
s2a_df$group2 <- gsub("\\(", "",s2a_df$group2)
s2a_df <- add_significance(s2a_df,p.col = "p.value")
s2a_df$Day <- "Day 29"

s2b_df <- as.data.frame(s2b$contrasts)
s2b_df$group1 <- "pLNA-Ctrl"
s2b_df$group2 <- s2b_df$contrast
s2b_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s2b_df$group2)
s2b_df$group2 <- gsub("\\(", "",s2b_df$group2)
s2b_df <- add_significance(s2b_df,p.col = "p.value")
s2b_df$Day <- "Day 36"

s2_df <- rbind(s2a_df,s2b_df)


y_pos <- c()
for(i in s2_df$Day) {
  ll <- max(ag_length[ag_length$Day == i,"x"])
  y_pos <- c(y_pos,ll)
}

s2_df$y_pos <- y_pos*1.05



p2 <- ggplot(ag_length,aes(x = Condition, y = x)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s2_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  facet_wrap(~Day) +
  ylab("MitoLength per Image [µm]") +
  theme_classic()+
  scale_color_manual(values = col_vec) +
  coord_cartesian(ylim = c(0,1.3)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))
  
ggsave2("../Figure_Output/SIM_MitoLength.png",p2, width = 7,height = 4.75, bg = "white")
ggsave2("../Figure_Output/SIM_MitoLength.pdf",p2, width = 7,height = 4.75, bg = "white")
```

```{r}
p2a <- p2 + coord_cartesian(ylim = c(0.7,1.25)) + theme(legend.position = "right")
ggsave2("../Figure_Output/SIM_MitoLength_zoom.png",p2a, width = 5,height = 4.75, bg = "white")
```



```{r}
legend <- get_legend(p1)

pp <- plot_grid(p1 + theme(legend.position="none"),
                p2 + theme(legend.position="none"),
                legend, rel_widths = c(1,1,0.3),nrow = 1)
ggsave2("../Figure_Output/SIM_summary.png",pp, width = 12,height = 3.75, bg = "white")
```



```{r}
#Intensity
ag_inten <- aggregate(e$Mito_MeanIntensity_SIM,e[,c("Differentiation","Condition","Image","Day")], FUN=mean)

mod_s3a <- lm(x ~ Condition + Differentiation,data = ag_inten[ag_inten$Day == "Day 29",])
s3a <- emmeans(mod_s3a, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s3b <- lm(x ~ Condition + Differentiation,data = ag_inten[ag_inten$Day == "Day 36",])
s3b <- emmeans(mod_s3b, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

mod_s3 <- lm(x ~ Condition*Day + Differentiation*Day,data = ag_inten)
s3 <- emmeans(mod_s3, trt.vs.ctrl ~ Condition | Day , ref="pLNA-Ctrl")

s3a_df <- as.data.frame(s3a$contrasts)
s3a_df$group1 <- "pLNA-Ctrl"
s3a_df$group2 <- s3a_df$contrast
s3a_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s3a_df$group2)
s3a_df$group2 <- gsub("\\(", "",s3a_df$group2)
s3a_df <- add_significance(s3a_df,p.col = "p.value")
s3a_df$Day <- "Day 29"

s3b_df <- as.data.frame(s3b$contrasts)
s3b_df$group1 <- "pLNA-Ctrl"
s3b_df$group2 <- s3b_df$contrast
s3b_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s3b_df$group2)
s3b_df$group2 <- gsub("\\(", "",s3b_df$group2)
s3b_df <- add_significance(s3b_df,p.col = "p.value")
s3b_df$Day <- "Day 36"

s3_df <- rbind(s3a_df,s3b_df)


y_pos <- c()
for(i in s3_df$Day) {
  ll <- max(ag_inten[ag_inten$Day == i,"x"])
  y_pos <- c(y_pos,ll)
}

s3_df$y_pos <- y_pos*1.05

p3 <- ggplot(ag_inten,aes(x = Condition, y = x)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  facet_wrap(~Day) +
  ggsignif::geom_signif(
    data = s3_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("Mito MeanIntensity per Image") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  coord_cartesian(ylim = c(0,NA)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figure_Output/SIM_MitoMeanIntensity.png",p3,width = 7,height = 4.75, bg = "white")
```







