---
title: "longRNA DEA SE generation"
author: "tgermade"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: 'cerulean'
    highlight: 'tango'
    df_print: paged
---
  
  <style>
  .main-container {
    max-width: 1500px !important;
  }
</style>
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}

suppressPackageStartupMessages({
  library(edgeR)
  library(SummarizedExperiment)
  library(SEtools)
})
```

## Allocation

```{r allocation}

# allocation

## filter: AT LEAST how many counts in AT LEAST how many samples? e.g. counts >= 10, samples >= 2
sel <- c(10, 2)
## input/output files
input <-"../data/Long_RNA/raw/longRNA.raw.SE.rds"
output <- "../data/Long_RNA/longRNA.DEA.SE.rds"
output.no_round <- "../data/Long_RNA/longRNA_noRound.DEA.SE.rds"
```

## Loading

```{r load se, warning=FALSE, message=FALSE}

# load raw SE file
se <- readRDS(input)
```

## Prep

```{r modify, message=FALSE, warning=FALSE, eval=TRUE}

# create batch variable
se$is.SC1 <- factor(se$experiment=="SC1")
# filter raw data
se <- se[which(rowSums(assay(se) >= sel[1]) >= sel[2]),]
```

```{r add assays function, message=FALSE, warning=FALSE, eval=TRUE}

logAssays <- function(se, control,output){
  ## SE object with logCPM & logFC assays
  assays(se)$logcpm <- log1p(cpm(calcNormFactors(DGEList(assay(se)))))
  se <- SEtools::log2FC(se, controls = se$stage==control, fromAssay = "logcpm", toAssay = output)
  return(se)
}
```

```{r add assays, message=FALSE, warning=FALSE, eval=TRUE}
se <- logAssays(se, 0, output = "log2FC.all")
se <- logAssays(se, 9, output = "log2FC.neur")
```

## PCA

```{r pca, message=FALSE, warning=FALSE, eval=TRUE}

# plot PCA to check for batch effect

## combined
plgINS::plPCA(assays(se)$logcpm, as.data.frame(colData(se)), colorBy = "stage", shapeBy = "experiment",
              add.labels = FALSE, annotation_columns = colnames(colData(se)))

```

```{r pca2, message=FALSE, warning=FALSE, eval=TRUE}

# plot PCA to check for batch effect

## combined
plgINS::plPCA(assays(se[,se$stage!=0])$logcpm, as.data.frame(colData(se)), colorBy = "stage", shapeBy = "experiment",
              add.labels = FALSE, annotation_columns = colnames(colData(se)))
```

## DEA over all stages

```{r dea all, message=FALSE, warning=FALSE, eval=TRUE}

# run DEA
source("../../functions/dea.R")

se <- DEA(se, name = "all", model = ~is.SC1 + stage, model0 = ~is.SC1)
```

## DEA over neuronal stages

```{r dea neuronal, message=FALSE, warning=FALSE, eval=TRUE}

se <- DEA(se, use = which(se$day > 0), name = "neuronal", model = ~is.SC1 + stage, model0 = ~is.SC1)
```

## pairwise DEA over all stages

```{r variables, eval=TRUE}

# define variables
stages <- unique(as.numeric(as.character(se$stage)))
dea.names <- c("9v0", "15v9", "21v15", "27v21", "33v27", "40v33")
```

```{r dea pairwise, eval=TRUE}

# do pairwise differential expression analysis for all stages
for(i in 1:length(dea.names)){
  se <- DEA(se, name = dea.names[i], use = se$stage %in% c(stages[i],stages[i+1]), 
            model = ~is.SC1 + stage, model0 = ~is.SC1)
}
```



## Pairwise comparison over all stages against Day0
```{r}
dea.names3 <- c("15v0", "21v0", "27v0", "33v0", "40v0")

# do pairwise differential expression analysis for all stages
for(i in 1:length(dea.names3)){
  se <- DEA(se, name = dea.names3[i], use = se$stage %in% c(stages[1],stages[i+2]), 
              model = ~stage)
}
```



## pairwise DEA 21v9 & 27v15

```{r}
# define names
dea.names2 <- c("21v9", "27v15")

# do pairwise differential expression analysis for these two specific stages
for(i in 1:length(dea.names2)){
  se <- DEA(se, name = dea.names2[i], use = se$stage %in% c(stages[i+1],stages[i+3]), 
              model = ~is.SC1 + stage, model0 = ~is.SC1)
}
```

## pairwise DEA 27v9
```{r}
se <- DEA(se, name = "27v9", use = se$stage %in% c(stages[2],stages[5]), 
              model = ~is.SC1 + stage, model0 = ~is.SC1)
```


## pairwise DEA 40v9
```{r}
se <- DEA(se, name = "40v9", use = se$stage %in% c(stages[2],stages[7]), 
              model = ~is.SC1 + stage, model0 = ~is.SC1)
```




## Export

```{r add libsize info, eval=TRUE}

# add library size info to colData
se$libsize <- colSums(assay(se))
```

```{r export se no_round, eval=TRUE}

# export unrounded
saveRDS(se, output.no_round)
```

```{r export se round, message=FALSE, warning=FALSE, eval=TRUE}

# round
source("../../functions/roundSE.R")
se <- roundSE(se)

# export rounded
saveRDS(se, output)
```



## Lists

```{r lists, eval=TRUE}

# lists of top transcripts based on FDR

## which columns not to print 
col_F <- sapply(rowData(se), FUN=function(x) colnames(x)=="F")
col_pval <- sapply(rowData(se), FUN=function(x) colnames(x)=="PValue")
col_symbol <- sapply(rowData(se), FUN=function(x) colnames(x)=="symbol")

## DEA all
head(rowData(se)$DEA.all[order(rowData(se)$DEA.all$FDR),
                         !(col_F$DEA.all | col_pval$DEA.all | col_symbol$DEA.all)], 10)

## DEA neuronal
head(rowData(se)$DEA.neuronal[order(rowData(se)$DEA.neuronal$FDR),
                              !(col_F$DEA.neuronal | col_pval$DEA.neuronal | 
                                  col_symbol$DEA.neuronal)], 10)

## DEA pairwise
dea.df.names <- paste0("DEA.",dea.names)
list_pw <- lapply(dea.df.names, FUN=function(x){
  rowData(se)[[x]][order(rowData(se)[[x]]$FDR), !(col_F[[x]] | col_pval[[x]] | col_symbol[[x]])]
})
names(list_pw) <- dea.df.names
lapply(list_pw, head, 10)
```


