---
title: "enrichMiR_Kleaveland_2018"
author: "Michael Soutschek"
date: "31 1 2021"
output: html_document
editor_options: 
  chunk_output_type: inline
---


```{r}
suppressPackageStartupMessages({
  library(enrichMiR)
  library(SummarizedExperiment)
  library(ggrepel)
  library(scales)
  library(cowplot)
})
```

#load enrichMiR Data
```{r}
#sets
sets_SC <- readRDS("V:/Michael/Bioinformatics/Reference/enrichMiR/scanMiR/scanMiR_GRCh38_gene.rds")
sets_TS <- readRDS("V:/Michael/Bioinformatics/Reference/enrichMiR/Targetscan/20211124_Targetscan8_Human_AllPred_human.rds")

#mir
se_short <- readRDS("../../../01_TimeCourse_MultiOmics/smallRNA/data/Small_RNA/smallRNA_oasis.DEA.SE.rds")
se_short_21 <- se_short[,se_short$day == 21]
se_short_21 <- se_short_21[grep("hsa-miR",row.names(se_short_21)),]

miRs <- as.data.frame(assays(se_short_21)$logcpm)
miRs <- rowMeans(miRs)
miRs <- miRs[miRs > 1.5]
```


#load experiment
```{r}
se <- readRDS("../data/SE.dea.Gene.salmon.raw.rds")

dea1229 <- rowData(se)[["DEA.pLNA-1229"]] 
dea181c <- rowData(se)[["DEA.pLNA-181c"]] 
dea3943 <- rowData(se)[["DEA.pLNA-3943"]] 
```

########
##EnrichMiR Tests


# enrichMiR 1229 (only present in TSall)
```{r}
enr_1229_SC <- testEnrichment(dea1229,sets = sets_SC,tests = c("areamir","siteoverlap"), sets.properties = miRs,th.FDR = 0.5)
res_1229_SC_ar <- getResults(enr_1229_SC,test = c("areamir"),flatten = TRUE)
res_1229_SC_so <- getResults(enr_1229_SC,test = c("siteoverlap.up"),flatten = TRUE)
#filter out miRNAs without family
res_1229_SC_so <- res_1229_SC_so[!is.na(res_1229_SC_so$members),]
```


# enrichMiR 3943 (sites only present in TSall)
```{r}
enr_3943_SC <- testEnrichment(dea3943,sets = sets_SC,tests = c("areamir","siteoverlap"), sets.properties = miRs,th.FDR = 0.5)
res_3943_SC_ar <- getResults(enr_3943_SC,test = c("areamir"),flatten = TRUE)
res_3943_SC_so <- getResults(enr_3943_SC,test = c("siteoverlap.up"),flatten = TRUE)
#filter out miRNAs without family
res_3943_SC_so <- res_3943_SC_so[!is.na(res_3943_SC_so$members),]
```


# enrichMiR 181
```{r}
enr_181_SC <- testEnrichment(dea181c,sets = sets_SC,tests = c("areamir","siteoverlap"), sets.properties = miRs, th.FDR = 0.5)
res_181_SC_ar <- getResults(enr_181_SC,test = c("areamir"),flatten = TRUE)
res_181_SC_so <- getResults(enr_181_SC,test = c("siteoverlap.up"),flatten = TRUE)
#filter out miRNAs without family
res_181_SC_so <- res_181_SC_so[!is.na(res_181_SC_so$members),]
```
# enrichMiR 181 (TargetScan)
```{r}
enr_181_TS <- testEnrichment(dea181c,sets = sets_TS,tests = c("areamir","siteoverlap"), sets.properties = miRs, th.FDR = 0.5)
res_181_TS_ar <- getResults(enr_181_TS,test = c("areamir"),flatten = TRUE)
res_181_TS_so <- getResults(enr_181_TS,test = c("siteoverlap.up"),flatten = TRUE)
#filter out miRNAs without family
res_181_TS_so <- res_181_TS_so[!is.na(res_181_TS_so$members),]
```


#########
## EnrichPlots

#EnrichPlot 1229
```{r}
#siteoverlap
p1 <- enrichPlot(res = res_1229_SC_so,enr.field = "enrichment",col.field = "props",sig.field = "FDR",label.field = "members", size.field = "overlap", label.sig.thres = 0.75)

#fix the axis labels
p1 <- p1 + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p1 <- p1 + scale_color_viridis_c(direction = 1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12)) + ggtitle("scanMiR can. - siteoverlap") + labs(color="Expression")

#areamir
p2 <- enrichPlot(res = res_1229_SC_ar,enr.field = "enrichment",col.field = "props",sig.field = "FDR", size.field = NULL, label.sig.thres = 0.05)

#fix the axis labels
p2 <- p2 + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p2 <- p2 + scale_color_viridis_c(direction = 1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12), legend.position = "bottom") + ggtitle("scanMiR can. - areamir") + labs(color="Expression") + guides(colour = guide_colourbar(title.position="left", title.hjust = 0.5))

legend <- get_plot_component(p2, 'guide-box-bottom', return_all = TRUE)

title1 <- ggdraw() + draw_label("DEA miR-1229", fontface='italic', size = 18)
pp1 <- plot_grid(p1+ theme(legend.position = "none"),
                 p2+ theme(legend.position = "none"), nrow = 1)
pp1_leg <- plot_grid(title1,NULL,pp1,legend,ncol = 1, rel_heights = c(0.05,0.05,1,0.1))
```

```{r}
ggsave2("../Figures/Figure_Output/EnrichMiR/miR1229_EnrichPlot_SO.png",p1, width = 7,height = 5, bg = "white")
ggsave2("../Figures/Figure_Output/EnrichMiR/miR1229_EnrichPlot_Comb.png",pp1_leg, width = 12,height = 5, bg = "white")
```


#EnrichPlot 181c
```{r}
#siteoverlap
p3 <- enrichPlot(res = res_181_SC_so,enr.field = "enrichment",col.field = "props",sig.field = "FDR",label.field = "members", size.field = "overlap", label.sig.thres = 0.0175)

#fix the axis labels
p3 <- p3 + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p3 <- p3 + scale_color_viridis_c(direction = 1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12)) + ggtitle("scanMiR can. - siteoverlap") + labs(color="Expression")

#areamir
p4 <- enrichPlot(res = res_181_SC_ar,enr.field = "enrichment",col.field = "props",sig.field = "FDR", size.field = NULL, label.sig.thres = 0.05)

#fix the axis labels
p4 <- p4 + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p4 <- p4 + scale_color_viridis_c(direction = 1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12), legend.position = "bottom") + ggtitle("scanMiR can. - areamir") + labs(color="Expression") + guides(colour = guide_colourbar(title.position="left", title.hjust = 0.5))

legend <- get_plot_component(p4, 'guide-box-bottom', return_all = TRUE)

title2 <- ggdraw() + draw_label("DEA miR-181", fontface='italic', size = 18)
pp2 <- plot_grid(p3+ theme(legend.position = "none"),
                 p4+ theme(legend.position = "none"), nrow = 1)
pp2_leg <- plot_grid(title2,NULL,pp2,legend,ncol = 1, rel_heights = c(0.05,0.05,1,0.1))
```

```{r}
ggsave2("../Figures/Figure_Output/EnrichMiR/miR181_EnrichPlot_SO.png",p3, width = 7,height = 5, bg = "white")
ggsave2("../Figures/Figure_Output/EnrichMiR/miR181_EnrichPlot_Comb.png",pp2_leg, width = 12,height = 5, bg = "white")
```



#EnrichPlot 181c TargetScan
```{r}
#siteoverlap
p3b <- enrichPlot(res = res_181_TS_so,enr.field = "enrichment",col.field = "props",sig.field = "FDR",label.field = "members", size.field = "overlap", label.sig.thres = 0.0175)

#fix the axis labels
p3b <- p3b + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p3b <- p3b + scale_color_viridis_c(direction = -1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12)) + ggtitle("TargetScan all - siteoverlap") + labs(color="Expression")

#areamir
p4b <- enrichPlot(res = res_181_TS_ar,enr.field = "enrichment",col.field = "props",sig.field = "FDR", size.field = NULL, label.sig.thres = 0.05, label.field = "members")

#fix the axis labels
p4b <- p4b + scale_y_continuous(
    trans  = enrichMiR:::.reverselog_trans(10),
    breaks = log_breaks(base = 10)
  )

p4b <- p4b + scale_color_viridis_c(direction = -1) + theme_classic() + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12), legend.position = "bottom") + ggtitle("TargetScan all - areamir") + labs(color="Expression") + guides(colour = guide_colourbar(title.position="left", title.hjust = 0.5))

legend <- get_plot_component(p4b, 'guide-box-bottom', return_all = TRUE)

title2 <- ggdraw() + draw_label("DEA miR-181", fontface='italic', size = 18)
pp2b <- plot_grid(p3b+ theme(legend.position = "none"),
                 p4b+ theme(legend.position = "none"), nrow = 1)
pp2b_leg <- plot_grid(title2,NULL,pp2b,legend,ncol = 1, rel_heights = c(0.05,0.05,1,0.1))
```

```{r}
ggsave2("../Figures/Figure_Output/EnrichMiR/miR181_EnrichPlot_TargetScan_SO.png",p3b, width = 7,height = 5, bg = "white")
ggsave2("../Figures/Figure_Output/EnrichMiR/miR181_EnrichPlot_TargetScan_Comb.png",pp2b_leg, width = 12,height = 5, bg = "white")
```








#######
##CD Plots


#CD Plot ScanMiR miR-1229
```{r}
#sites
set_1229 <- "hsa-miR-1229-3p"

p3 <- CDplotWrapper(dea = dea1229, sets = sets_SC, setName = set_1229, by = "best_stype") + coord_cartesian(xlim = c(-0.35,0.35)) + theme_classic() + ggtitle("miR-1229-3p") + guides(color=guide_legend(title="scanMiR\nbest site type")) + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12))

ggsave2("../Figures/Figure_Output/EnrichMiR/miR1229_CDPlot_SC.png",p3, width = 5,height = 4.5, bg = "white")
```




#CD Plot ScanMiR miR-3943
```{r}
#sites
set_3943 <- "hsa-miR-3943"

p4 <- CDplotWrapper(dea = dea3943, sets = sets_SC, setName = set_3943, by = "best_stype") + coord_cartesian(xlim = c(-0.35,0.35)) + theme_classic() + ggtitle("miR-3943") + guides(color=guide_legend(title="scanMiR\nbest site type")) + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12))

ggsave2("../Figures/Figure_Output/EnrichMiR/miR3943_CDPlot_SC.png",p4, width = 5,height = 4.5, bg = "white")
```



#CD Plot ScanMiR miR-181
```{r}
#sites
set_181 <- "hsa-miR-181c-5p"

p5 <- CDplotWrapper(dea = dea181c, sets = sets_SC, setName = set_181, by = "best_stype") + coord_cartesian(xlim = c(-0.35,0.35)) + theme_classic() + ggtitle("miR-181c-5p") + guides(color=guide_legend(title="scanMiR\nbest site type")) + theme(plot.title = element_text(size=15), axis.text=element_text(size=12), axis.title=element_text(size=14),legend.title=element_text(size=13), legend.text=element_text(size=12))

ggsave2("../Figures/Figure_Output/EnrichMiR/miR181_CDPlot_SC.png",p5, width = 5,height = 4.5, bg = "white")
```


