---
title: "Segmentation_Quantification"
author: "Michael Soutschek"
date: "2024-06-25"
output: html_document
---

#libraries
```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(scales)
  library(ggsci)
  library(cowplot)
})
```


## Individual Mitochondria

#Data Import
```{r}
nv11 <- read.csv("../../05_cellprofiler/cp_out_nv11/20250717_nv11_PKMDR_Mitochondria.csv")
nv12 <- read.csv("../../05_cellprofiler/cp_out_nv12/20250717_nv12_PKMDR_Mitochondria.csv")
nv13 <- read.csv("../../05_cellprofiler/cp_out_nv13/20250717_nv13_PKMDR_Mitochondria.csv")
```

```{r}
all_tables <- list("nv11" = nv11,"nv12" = nv12,"nv13" = nv13)
```

#check whether all file names are correct

```{r}
all_check <- list()
```

```{r}
#remove two headers
for (i in names(all_tables)){
  j <- all_tables[[i]]
  j <- j[,grep("FileName",as.character(j[1,]))]
  colnames(j) <- as.character(j[1,])
  j <- j[-1,]
  all_check[[i]] <- j
}

check <- do.call(rbind,all_check)
row.names(check) <- NULL
```

```{r}
for (i in colnames(check)[grep("FileName",colnames(check))]) {
  check[[i]] <- gsub("raw_mip_","",check[[i]])
  check[[i]] <- gsub("Channel1_Probabilities_C1-decon_mip_","",check[[i]])
  check[[i]] <- gsub("Channel1_Probabilities_C3-decon_mip_","",check[[i]])
}
  
check$correct_name <- apply(check[,colnames(check)], 1, function(row) length(unique(row)) == 1)
all(check$correct_name == "TRUE")
```

#CleanUp

```{r}
all_tables_clean <- list()
```


```{r}
#remove two headers
for (i in names(all_tables)){
  j <- all_tables[[i]]
  j <- j[,-grep("PathName_",as.character(j[1,]))]
  j <- j[,-grep("FileName_[pr]",as.character(j[1,]))]
  j <- j[,-grep("Number",as.character(j[1,]))]
  colnames(j) <- paste(colnames(j),as.character(j[1,]),sep ="_")
  j <- j[-1,]
  colnames(j)[which(grepl("FileName",colnames(j)))] <- "FileName"
  all_tables_clean[[i]] <- j
}

res_mito <- do.call(rbind,all_tables_clean)
row.names(res_mito) <- NULL
```


```{r}
#naming
colnames(res_mito)[which(grepl("Skeleton",colnames(res_mito)))] <- "Length"
colnames(res_mito)[which(grepl("AreaShape",colnames(res_mito)))] <- "Area"
colnames(res_mito)[which(grepl("Intensity",colnames(res_mito)))] <- "Intensity_Calcium"
colnames(res_mito)[which(grepl("Children",colnames(res_mito)))] <- "Count_mtDNA"
colnames(res_mito)[which(grepl("Parent",colnames(res_mito)))] <- "InSoma"
```

```{r}
#Infos1
res_mito$Compartment <- ifelse(res_mito$InSoma > 0,"Soma","Processes")
res_mito$mtDNA <- ifelse(res_mito$Count_mtDNA > 0,"yes","no")
```

```{r}
#formating
res_mito$Length <- as.numeric(res_mito$Length)
res_mito$Area <- as.numeric(res_mito$Area)
res_mito$Intensity_Calcium <- as.numeric(res_mito$Intensity_Calcium)
res_mito$Count_mtDNA <- as.numeric(res_mito$Count_mtDNA)
res_mito$InSoma <- as.numeric(res_mito$InSoma)

res_mito$Compartment <- factor(res_mito$Compartment, levels = c("Processes","Soma"))
res_mito$mtDNA <- factor(res_mito$mtDNA, levels = c("yes","no"))
```

```{r}
#Check for your images!!
res_mito$Area_um <- res_mito$Area / (21.7391^2)
res_mito$Length_um <- res_mito$Length / 21.7391
```

```{r}
#Infos2
res_mito$mtDNA_Density_inMito <- res_mito$Count_mtDNA / res_mito$Area_um 
res_mito$mtDNA_Density_inMito <- as.numeric(res_mito$mtDNA_Density_inMito)
```


##experimental condition

#blinding
```{r}
res_mito$blinding <- paste0(sapply(strsplit(res_mito$FileName,"_"),"[",5),"_",sapply(strsplit(res_mito$FileName,"_"),"[",6))
res_mito$blinding <- gsub(".tif","",res_mito$blinding)
```

```{r}
blind <- readRDS("../../250715_blinding_mtdna.rds")
blind$check <- NULL
blind$blinding <- gsub("raw_mip_","",blind$blinding)
```

```{r}
res_mito <- merge(res_mito,blind,by = "blinding", all.x = TRUE)
```

```{r}
res_mito <- res_mito[,-grep("FileName",colnames(res_mito))]
```


#experimental condition
```{r}
res_mito$Condition <- sapply(strsplit(res_mito$file,"_"),"[",8)
res_mito$Diff <- sapply(strsplit(res_mito$file,"_"),"[",2)
res_mito$ImageNumber <- sapply(strsplit(res_mito$file,"_"),"[",9)
res_mito$ImageNumber <- gsub(".vsi","",res_mito$ImageNumber)
```

```{r}
res_mito$Diff <- factor(res_mito$Diff, levels = c("Nv11","Nv12","Nv13"))
res_mito$Condition <- factor(res_mito$Condition, levels = c("Ctrl","1229"))
```


```{r}
saveRDS(res_mito,"../Data/mito_res.rds")
```
