---
title: "longRNA-exploratory"
author: "Michael Soutschek"
date: "11 1 2021"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(plotly)
  library(cowplot)
  library(ggsci)
  library(readxl)
})
```


# Color Definitions
```{r}
ancols <- list(diff=c( "p1"="#3F3F3F",
                       "p2" ="#707070",
                       "p3" ="#898989",
                       "p4" = "#A1A1A1"
) )

heatcol = viridis(255)
heatcol <- c("#2EBCD1","#252525","#D1432E")
heatcol <- c("#4B0C6B","#CF4446","#FFAD33")
```



# Load Data
```{r}
se <- readRDS("../../data/SE.dea.Gene.salmon.raw.rds")
se2 <- se[,se$condition != "pLNA-3943"]
row.names(se2) <- sapply(strsplit(row.names(se2),"\\."),"[",2)
```



#1229 Heatmaps
```{r}
dea1229 <- rowData(se)[["DEA.pLNA-1229"]]
dea1229$names <- row.names(dea1229)
dea1229.sig <- dea1229[dea1229$FDR < 0.05,]
dea1229.sig05 <- dea1229[dea1229$FDR < 0.5,]
length(dea1229.sig[dea1229.sig$logFC > 0,"names"])
dea1229.sig <- dea1229.sig[order(dea1229.sig$FDR),]
row.names(dea1229.sig) <- sapply(strsplit(row.names(dea1229.sig),"\\."),"[",2)

deaTop30 <- row.names(dea1229.sig[1:30,])

png("../Figure_Output/Heatmaps/Expl_1229_sig_Top30.png", width=8.5, height=6, units="in", res=300)
sechm::sechm(se2, deaTop30 , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition" ,breaks=TRUE, show_rownames = TRUE, anno_colors = ancols, hmcols = heatcol, annocol_title_side=NA, do.scale = TRUE,sortRowsOn=NULL, cluster_rows=FALSE)
dev.off()
```



```{r}
dea1229.sigup <- dea1229[dea1229$PValue < 0.05 & dea1229$logFC > 0,]
row.names(dea1229.sigup) <- sapply(strsplit(row.names(dea1229.sigup),"\\."),"[",2)

se3 <- se2[,se2$condition %in% c("pLNA-Ctrl","pLNA-1229")]

png("../Figure_Output/Heatmaps/Expl_1229_sig_up.png", width=9, height=7, units="in", res=300)
sechm::sechm(se2, row.names(dea1229.sigup) , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition" ,breaks=TRUE, show_rownames = FALSE, anno_colors = ancols, hmcols = heatcol, annocol_title_side=NA, do.scale = TRUE,sortRowsOn=NULL, cluster_rows=FALSE, 
             name = "scaled\nexpression", row_title = "pLNA-1229: p.value < 0.05 & logFC > 0")
dev.off()
```




#Mitochondrial genes
```{r}
MT_genes1 <- row.names(se2)[grep(pattern = "MT-",row.names(se2))]
MT_genes2 <- row.names(se2)[grep(pattern = "NDU",row.names(se2))]
se2$diff <- as.factor(se2$diff)

png("../Figure_Output/Heatmaps/Mitochondrial_Genes.png", width=9, height=7, units="in", res=300)
sechm::sechm(se2, MT_genes1, assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=FALSE, do.scale = TRUE, show_rownames = TRUE, anno_colors = ancols, hmcols = heatcol, annocol_title_side=NA, name = "scaled\nexpression")
dev.off()

png("../Figure_Output/Heatmaps/Mitochondrial_Genes_defense.png", width= 8.5, height=6, units="in", res=300)
sechm::sechm(se2, MT_genes1, assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=FALSE, do.scale = TRUE, show_rownames = TRUE, anno_colors = ancols, hmcols = heatcol, annocol_title_side=NA)
dev.off()

ls <- list("Mitochondria encoded"= MT_genes1, "Complex I - Nuclear encoded" = MT_genes2)

png("../Figure_Output/Heatmaps/Mitochondrial_Genes_withNuclear.png", width=9, height=16, units="in", res=300)
sechm::sechm(se2, ls , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=TRUE, show_rownames = TRUE, anno_colors = ancols, name = "logFC",
             hmcols = heatcol, annorow_title_side = "left")
dev.off()
```

#TFAM targets
```{r}
collecTRI.regulons <- readRDS("../../longRNA_R/TF_analysis/collecTRI.regulons.rds")
e <- collecTRI.regulons[collecTRI.regulons$source == "TFAM",]


ls <- list("TFAM predicted regulon"= e$target, "Mitochondrial\nTranscription Complex" = c("POLRMT","TEFM","MTERF1","TFB2M"))
ls <- list("TFAM predicted regulon"= e$target)

png("../Figure_Output/Heatmaps/TFAM_targets.png", width=8.5, height=6, units="in", res=300)
sechm::sechm(se2, ls, assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=FALSE, do.scale = FALSE, show_rownames = TRUE,hmcols = heatcol, anno_colors = ancols, annocol_title_side=NA, name = "logFC")
dev.off()
```


#Autophagy genes
```{r}
AT_genes <- grep(pattern = "ATG",row.names(se))

png("../Figure_Output/Heatmaps/Autophagy_Genes.png", width=9, height=6, units="in", res=300)
sechm::sechm(se, AT_genes, assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition" ,breaks=TRUE, show_rownames = TRUE)
dev.off()
```



#181 Heatmaps
```{r}
dea181c <- rowData(se)[["DEA.pLNA-181c"]]
dea181c$names <- row.names(dea181c)
dea181c.sig <- dea181c[dea181c$FDR < 0.05,]
dea181c.sig05 <- dea181c[dea181c$FDR < 0.5,]
row.names(dea181c.sig) <- sapply(strsplit(row.names(dea181c.sig),"\\."),"[",2)

png("../Figure_Output/Heatmaps/Expl_181c_sig.png", width=9, height=8, units="in", res=300)
sechm::sechm(se2, row.names(dea181c.sig), assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition" ,breaks=TRUE, show_rownames = TRUE, anno_colors = ancols, hmcols = heatcol, annocol_title_side=NA, name = "logFC", 
             row_title = "pLNA-181c: FDR < 0.05") 
dev.off()
```




#3943 Heatmaps
```{r}
dea3943 <- rowData(se)[["DEA.pLNA-3943"]]
dea3943$names <- row.names(dea3943)
dea3943.sig <- dea3943[dea3943$FDR < 0.1,]

png("../Figure_Output/Heatmaps/Expl_3943_sig.png", width=9, height=3, units="in", res=300)
sechm::sechm(se, row.names(dea3943.sig), assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition" ,breaks=TRUE, show_rownames = TRUE, do.scale = TRUE, anno_colors = ancols,
             hmcols = heatcol, annocol_title_side=NA) 
dev.off()
```



#MitoCarta genes
```{r}
MC_raw <- read_excel("../../data/230919_Human.MitoCarta3.0.xls", 
    sheet = "A Human MitoCarta3.0")
MC_genes <- MC_raw$Symbol


png("../Figure_Output/Heatmaps/MitoCarta_Genes_all.png", width=9, height=11, units="in", res=300)
sechm::sechm(se2, MC_genes , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=TRUE, show_rownames = FALSE, anno_colors = ancols,
             hmcols = heatcol, annorow_title_side = "left", annocol_title_side=NA, row_title = "MitoCarta 3.0 (all)")
dev.off()


dea1229.sig05$Symbol <- sapply(str_split(dea1229.sig05$names,"\\."),"[",2)
MC_genes_sig <- MC_genes[MC_genes %in% dea1229.sig05$Symbol]
MC_raw_sig <- MC_raw[MC_raw$Symbol %in% MC_genes_sig,]

png("../Figure_Output/Heatmaps/MitoCarta_Genes_FDR05.png", width=9, height=8, units="in", res=300)
sechm::sechm(se2, MC_genes_sig , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", breaks=TRUE, show_rownames = TRUE, anno_colors = ancols, 
             hmcols = heatcol, annorow_title_side = "left", annocol_title_side=NA, row_title = "MitoCarta 3.0 (pLNA-1229 FDR < 0.5)")
dev.off()

png("../Figure_Output/Heatmaps/MitoCarta_Genes_FDR05_scaled.png", width=9, height=8, units="in", res=300)
sechm::sechm(se2, MC_genes_sig , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", do.scale = TRUE, breaks=TRUE, show_rownames = TRUE, anno_colors = ancols,name = "scaled\nexpression", 
             hmcols = heatcol, annorow_title_side = "left", annocol_title_side=NA, row_title = "MitoCarta 3.0 (pLNA-1229 FDR < 0.5)")
dev.off()

dea1229.sig$Symbol <- sapply(str_split(dea1229.sig$names,"\\."),"[",2)
MC_genes_sig2 <- MC_genes[MC_genes %in% dea1229.sig$Symbol]

png("../Figure_Output/Heatmaps/MitoCarta_Genes_FDR005_scaled.png", width=9, height=8, units="in", res=300)
sechm::sechm(se2, MC_genes_sig2 , assayName ="log2FC.Ctrl", top_annotation="diff", gaps_at="condition", do.scale = TRUE, breaks=TRUE, show_rownames = TRUE, anno_colors = ancols,
             hmcols = heatcol, annorow_title_side = "left", annocol_title_side=NA, row_title = "MitoCarta 3.0 (pLNA-1229 FDR < 0.05)")
dev.off()
```














