---
title: "Plot_Targets"
author: "Michael Soutschek"
date: "7/24/2023"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(enrichMiR)
  library(scanMiR)
  library(scanMiRData)
  library(scanMiRApp)
  library(Biostrings)
  library(ggsci)
  library(cowplot)
})

```

```{r}
dea1229 <- read.csv("../pLNA_GRCh38.p13_Ens107/pLNA_experiment/Target_Analysis/miR1229/target_data/dea1229_targets_genebased.csv")
```




```{r}
findGO("macroautophagy")

#"macroautophagy"
genes <- getGOgenes("GO:0016236","Hs")

# # #"autophagy of mitochondrion" 
# genes <- getGOgenes("GO:0000422","Hs")

# "mitochondrial fission" 
# genes <- getGOgenes("GO:0000266","Hs")


genes <- genes[[1]]
```


```{r}
aut <- dea1229[dea1229$gene_name %in% genes,]
aut <- aut[aut$X8mer > 0 | aut$X7mer >0,]
aut <- aut[!is.na(aut$gene_id),]
aut <- aut[aut$PValue < 0.05,]
aut <- aut[aut$logFC > 0,]

write.csv(aut,"./autophagy_genes.csv")
```



# MiR-1229
```{r}
anno <- scanMiRApp::ScanMiRAnno("GRCh38")
hsa <- getKdModels("hsa")
```

```{r}
colvec <- enrichMiR:::.siteTypeColors()
colvec["8mer"] <- pal_uchicago("default")(9)[3]
```


.siteTypeColors <- function(){
  c(`no site` = "#000004FF",
    `6mer` = "#3A0963FF",
    `7mer-1a` = "#A92E5EFF",
    `7mer-a1` = "#A92E5EFF",
    `7mer` = "#A92E5EFF",
    `7mer-m8` = "#E65D2FFF",
    `8mer` = "#F5DB4BFF")
}



```{r}
mod <- anno$models$`hsa-miR-1229-3p`
seqs <- DNAStringSet(
  c(Pink1=getTranscriptSequence(aut$transcript[1], anno, extract = "UTRonly")[[1]],
    Atg12=getTranscriptSequence(aut$transcript[2], anno, extract = "UTRonly")[[1]],
    Csnk2a1=getTranscriptSequence(aut$transcript[3], anno, extract = "UTRonly")[[1]],
    Vcp=getTranscriptSequence(aut$transcript[4], anno, extract = "UTRonly")[[1]]
    ))

sf <- data.frame(start=1, end=lengths(seqs), seqnames=names(seqs), y=0)
m <- findSeedMatches(seqs, mod, onlyCanonical= TRUE, shadow = 15,maxLogKd = c(-0.3,-0.3))
m2 <- as.data.frame(m)
m2$position <- m2$start
m2$miRNA <- "miR-1229-3p"

```



```{r}
m2$seqnames <- factor(m2$seqnames, levels = c("Pink1","Atg12","Csnk2a1","Vcp"))
sf$seqnames <- factor(sf$seqnames, levels = c("Pink1","Atg12","Csnk2a1","Vcp"))

p <- ggplot(m2, aes(colour=type)) + 
  geom_segment(data=sf, aes(x=start, xend=end, y=y, yend=y), colour="black") + 
  facet_wrap(~seqnames, scales = "free_x", ncol=1) + theme_minimal() +
  geom_segment(aes(x=position, xend=position, y=0, yend=-log_kd/1000), size=2) +
  geom_label(aes(x=position, y=-log_kd/1000, label=type)) +
  labs(y=bquote(-log(K[D])), x="Position on UTR") + 
  scale_y_continuous(limits=c(-0.5,6.5), breaks=c(0,1,3,5)) +
  scale_x_continuous(expand=expansion(mult = c(.033,.033))) + theme(strip.text=element_text(face="bold") ) +
  scale_color_manual(values = colvec) +
  theme_classic() +
  ggtitle("Upregulated macroautophagy genes with miR-1229-3p binding sites") +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.text.x = element_text(size = rel(1)),
        plot.margin = unit(c(1,2,1,1),"lines"))


ggsave2("./Autophagy_Targets.png",p, width = 10,height = 10, bg = "white")
```















