---
title: "smallRNA DEA SE generation"
author: "tgermade"
date: "`r Sys.Date()`"
output:
    html_document:
        toc: true
        toc_float: true
        theme: 'cerulean'
        highlight: 'tango'
        df_print: paged
---

<style>
  .main-container {
    max-width: 1500px !important;
  }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}
suppressPackageStartupMessages({
  library(edgeR)
  library(SummarizedExperiment)
  library(SEtools)
})
```


## Allocation

```{r allocation}

# allocation

## input/output files
input <- "../data/Small_RNA/raw/smallRNA_oasis.raw.SE.rds"
output <- "../data/Small_RNA/smallRNA_oasis.DEA.SE.rds"
output.no_round <- "../data/Small_RNA/smallRNA_oasis_noRound.DEA.SE.rds"
```


## Loading

```{r load se, warning=FALSE, message=FALSE}

# load raw SE file
se <- readRDS(input)
# remove first 5 rows (they're overall dataset stats)
se <- se[-c(1:5)]

# filter: AT LEAST how many counts in AT LEAST how many samples? e.g. counts >= 20, samples >= 1
## Could potentially be redone with counts >= 10, samples >= 3
se <- se[rowSums(assay(se)>=10)>3,]
```


```{r add assays function, message=FALSE, warning=FALSE, eval=TRUE}
logAssays <- function(se, control,output){
  ## SE object with logCPM & logFC assays
  assays(se)$logcpm <- log1p(cpm(calcNormFactors(DGEList(assay(se)))))
  se <- SEtools::log2FC(se, controls = se$stage==control, fromAssay = "logcpm", toAssay = output)
  return(se)
}
```

```{r add assays, message=FALSE, warning=FALSE, eval=TRUE}
se <- logAssays(se, 0, output = "log2FC.all")
se <- logAssays(se, 9, output = "log2FC.neur")
```



## DEA over all stages

```{r dea all, message=FALSE, warning=FALSE, eval=TRUE}

# run DEA
source("../../functions/dea.R")

se <- DEA(se, name = "all", model = ~stage)
```


## DEA over neuronal stages

```{r dea neuronal, message=FALSE, warning=FALSE, eval=TRUE}

# run DEA
source("../../functions/dea.R")

se <- DEA(se, use = which(se$day > 0), name = "neuronal", model = ~stage)
```


## pairwise DEA over all stages

```{r variables, eval=TRUE}

# define variables
stages <- unique(as.numeric(as.character(se$stage)))
dea.names <- c("9v0", "15v9", "21v15", "27v21", "33v27", "40v33")
```

```{r dea pairwise, eval=TRUE}

# do pairwise differential expression analysis for all stages
for(i in 1:length(dea.names)){
  se <- DEA(se, name = dea.names[i], use = se$stage %in% c(stages[i],stages[i+1]), 
              model = ~stage)
}
```

## pairwise DEA 21v9 & 27v15

```{r}
# define names
dea.names2 <- c("21v9", "27v15")

# do pairwise differential expression analysis for these two specific stages
for(i in 1:length(dea.names2)){
  se <- DEA(se, name = dea.names2[i], use = se$stage %in% c(stages[i+1],stages[i+3]), 
              model = ~stage)
}
```


## Pairwise comparison over all stages against Day0
```{r}
dea.names3 <- c("15v0", "21v0", "27v0", "33v0", "40v0")

# do pairwise differential expression analysis for all stages
for(i in 1:length(dea.names3)){
  se <- DEA(se, name = dea.names3[i], use = se$stage %in% c(stages[1],stages[i+2]), 
              model = ~stage)
}
```


## pairwise DEA 40v9
```{r}
se <- DEA(se, name = "40v9", use = se$stage %in% c(stages[2],stages[7]), 
              model = ~stage)
```


## pairwise DEA 27v9
```{r}
se <- DEA(se, name = "27v9", use = se$stage %in% c(stages[2],stages[5]), 
              model = ~stage)
```



## Export

```{r add libsize info, eval=TRUE}

# add library size info to colData
se$libsize <- colSums(assay(se))
```

```{r export se no_round, eval=TRUE}

# export unrounded
saveRDS(se, output.no_round)
```

```{r export se round, message=FALSE, warning=FALSE, eval=TRUE}

# round
source("../functions/roundSE.R")
se <- roundSE(se)

# export rounded
saveRDS(se, output)
```

