---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(MASS)
})
```



```{r}
show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[4],pal_uchicago("default")(9)[5])
```


#Load Data

```{r}
e <- readRDS("../data/TMRE_Data.rds")
```

```{r}
soma <- e[e$Parent_SomaEx > 0,]
proc <- e[e$Parent_SomaEx == 0,]
```






#### Soma

#preparations
```{r}
#aggregate
ag_s <- aggregate(soma$Intensity_MeanIntensity_cropRaw,soma[,c("Diff","sample","image")], FUN=mean)
ag_s_mean <- aggregate(ag_s$x,ag_s[,c("Diff","sample")], FUN=mean)

#normalize to pLNA-Ctrl
ag_s_mean_ctrl <- ag_s_mean[ag_s_mean$sample == "pLNA-Ctrl",]
colnames(ag_s_mean_ctrl)[3] <- "Ctrl"
ag_s <- merge(ag_s,ag_s_mean_ctrl[,c("Diff","Ctrl")],by = c("Diff"), all.x = TRUE)
ag_s$norm <- ag_s$x / ag_s$C
```


#statistics
```{r}
mod_s1 <- lm(x ~ sample + Diff,ag_s)
summary(mod_s1)
s1 <- emmeans(mod_s1, trt.vs.ctrl ~ sample , ref="pLNA-Ctrl")
s1


s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "pLNA-Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\ - \\(pLNA-Ctrl\\)","",s1_df$group2)
s1_df$group2 <- gsub("\\(", "",s1_df$group2)
s1_df$group2 <- gsub("\\)", "",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")
s1_df$p.value.signif <- round(s1_df$p.value,2)

#add y_position
y_pos <- max(ag_s[,"norm"])

s1_df$y_pos <- y_pos*1.1
```


```{r}
p1 <- ggplot(ag_s,aes(x = sample, y = norm)) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  coord_cartesian(ylim = c(0,2.25)) +
  ylab("TMRE intensity in soma\n(mean per image, normlized to pLNA-Ctrl)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../../FigureOutput/Soma_Intensity.png",p1, width = 6,height = 5, bg = "white")
```


### Processes

#preparations
```{r}
#aggregate
ag_p <- aggregate(proc$Intensity_MeanIntensity_cropRaw,proc[,c("Diff","sample","image")], FUN=mean)
ag_p_mean <- aggregate(ag_p$x,ag_p[,c("Diff","sample")], FUN=mean)

#normalize to pLNA-Ctrl
ag_p_mean_ctrl <- ag_p_mean[ag_p_mean$sample == "pLNA-Ctrl",]
colnames(ag_p_mean_ctrl)[3] <- "Ctrl"
ag_p <- merge(ag_p,ag_p_mean_ctrl[,c("Diff","Ctrl")],by = c("Diff"), all.x = TRUE)
ag_p$norm <- ag_p$x / ag_p$C
```


#statistics
```{r}
mod_s1 <- lm(x ~ sample + Diff,ag_p)
summary(mod_s1)
s1 <- emmeans(mod_s1, trt.vs.ctrl ~ sample , ref="pLNA-Ctrl")
s1


s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "pLNA-Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\ - \\(pLNA-Ctrl\\)","",s1_df$group2)
s1_df$group2 <- gsub("\\(", "",s1_df$group2)
s1_df$group2 <- gsub("\\)", "",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")
s1_df$p.value.signif <- round(s1_df$p.value,2)

#add y_position
y_pos <- max(ag_p[,"norm"])

s1_df$y_pos <- y_pos*1.1
```


```{r}
p2 <- ggplot(ag_p,aes(x = sample, y = norm)) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35), size = 0.75
  ) +
  coord_cartesian(ylim = c(0,1.5)) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("TMRE intensity in processes\n(mean per image, normlized to pLNA-Ctrl)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../../FigureOutput/Processes_Intensity.png",p2, width = 6,height = 5, bg = "white")
```



