---
title: "Proteomics_Figures"
author: "Michael Soutschek"
date: "11 1 2021"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(DEP)
  library(limma)
  library(sechm)
})
```

# Colors
```{r}
heatcol3 = inferno(255)

# ancols <- list(condition=c("iPSC"="#3F3F3F",
#                         "N_09" ="#575757",
#                         "N_15" ="#707070",
#                         "N_21" = "#898989",
#                         "N_27" ="#A1A1A1",
#                         "N_33" ="#BABABA",
#                         "N_40" = "#D3D3D3" 
#                         ) )
# 
# ancols2 <- list(condition=c("N_09" ="#575757",
#                         "N_15" ="#707070",
#                         "N_21" = "#898989",
#                         "N_27" ="#A1A1A1",
#                         "N_33" ="#BABABA",
#                         "N_40" = "#D3D3D3" 
#                         ) )

ancols <- list(day=c("0"="#3F3F3F",
                       "9" ="#575757",
                       "15" ="#707070",
                       "21" = "#898989",
                       "27" ="#A1A1A1",
                       "33" ="#BABABA",
                       "40" = "#D3D3D3" 
) )
```




# Load and Prepare Data
```{r}
se_prot <- readRDS(file="../../Proteomics/data/Proteomics/Proteomics.Reference.SE_DEA.rds")
se_prot$day <- as.factor(se_prot$day)
se_prot2 <- se_prot[,which(se_prot$day!=0)]

resp <- rowData(se_prot)$DEA.all
resp2 <- rowData(se_prot)$DEA.neuronal
```


# Significants
```{r}
sigp_all <- row.names(resp)[which(resp$adj.P.Val < 0.05)]
sigp <- row.names(resp)[which(resp$adj.P.Val < 0.01)]
sigp2 <- row.names(resp2)[which(resp2$adj.P.Val < 0.01)]
```



## Figures

# Heatmap all days
```{r}
# sehm(se_prot, sigp, anno_columns=c("condition"), assayName = "logFC", gaps_at = "condition", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol3, anno_colors = ancols,annotation_names_col = FALSE)
# 
# png("Figure Output/Proteomics_sig_alldays.png", width=7, height=5, units="in", res=300)
# sehm(se_prot, sigp, anno_columns=c("condition"), assayName = "logFC", gaps_at = "condition", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol3, anno_colors = ancols,annotation_names_col = FALSE)
# dev.off()
```

# Heatmap all days, normalized Day9
```{r}
png("Figure_Output/Exploratory/Proteomics_sig_alldays_normDay9.png", width=7, height=5, units="in", res=300)
sechm(se_prot, sigp, top_annotation =c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol3, anno_colors = ancols, column_title = "Proteins", annocol_title_side=NA, name = "logFC", cluster_rows = TRUE)
dev.off()
```





# Heatmap neuronal days,
```{r}
# a <- sechm(se_prot2, sigp2, assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol3, anno_colors = ancols, top_annotation = c("day"), column_title = "proteins", annocol_title_side = NA)
# 
# png("./Figure_Output/Proteomics_sig_neur_days.png", width=7, height=5, units="in", res=300)
# a
# dev.off()
```


#heatmap ribosomal proteins
```{r}
se_ribo <- se_prot2
row.names(se_ribo) <- rowData(se_ribo)$GeneName

Ribo_genes <- unique(rowData(se_ribo)[grep("^RPL|^RPS",rowData(se_ribo)$GeneName),]$GeneName)
mRibo_genes <- unique(rowData(se_ribo)[grep("^MRPL|^MRPS",rowData(se_ribo)$GeneName),]$GeneName)

heatcol <- c("#4B0C6B","#CF4446","#FFAD33")

png("./Figure_Output/RiboProteins_Protein.png", width=6, height=7, units="in", res=300)
draw(
  sechm(se_ribo, assayName = "log2FC.neur", features = Ribo_genes, do.scale = TRUE, top_annotation = "day", hmcols = heatcol,anno_colors = ancols, row_title="nuclear",heatmap_legend_param = list(title = "scaled\nexpression"), annocol_title_side=NA) %v% 
  sechm(se_ribo, assayName = "log2FC.neur", features = mRibo_genes, do.scale = TRUE, top_annotation = "day", hmcols = heatcol,anno_colors = ancols, row_title="mitochondrial", show_rownames = FALSE,heatmap_legend_param = list(title = "scaled logFC"),annocol_title_side=NA),
merge_legends=TRUE,column_title = "Ribosomal Proteins")
dev.off()
```










