---
title: "longRNA-exploratory"
author: "Michael Soutschek"
date: "11 1 2021"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(plotly)
  library(ggsci)
  library(dplyr)
  library(tibble)
  library(scales)
})
```


# Load Data
```{r}
se <- readRDS("../../Proteomics/data/Proteomics/Proteomics.Reference.SE_DEA.rds")
se$condition <- as.factor(se$condition)
se$Day <- paste0("Day ",se$day)
se$Day[which(se$Day == "Day 9")] <- "Day 09"
se$Day <- factor(se$Day, levels = c("Day 0","Day 09","Day 15","Day 21","Day 27","Day 33","Day 40"))
```

```{r}
replacement <- c("1" = "s1", "2" = "s2", "3" = "s3")
se$experiment <- replacement[as.character(se$replicate)]
se$experiment  <- factor(se$experiment ,levels = c("s1","s2","s3"))
```

```{r}
se2 <- se[,se$day != 0]
```


#Single genes
```{r}
g1 <- row.names(se)[rowData(se)$GeneName %in% "SYN1"]
g2 <- row.names(se)[grep("MT-", rowData(se)$GeneName)]

ggplot(meltSE(se, g2, assayName = "imputed"), aes(condition, imputed)) + geom_violin() + geom_point(aes(color = replicate)) +  facet_wrap(~feature, scale="free")

png("./Figure_Output/SingleGenes/SYN1.png", width=10, height=6, units="in", res=300)
ggplot(meltSE(se, g1, assayName = "imputed"), aes(condition, imputed)) + geom_violin() + geom_point(aes(color = experiment)) +  facet_wrap(~feature, scale="free") + theme_classic()
dev.off()
```



## PCA

```{r pca, message=FALSE, warning=FALSE, eval=TRUE}

# ## all stages
# p <- plgINS::plPCA(assays(se)$imputed, as.data.frame(colData(se)), colorBy = "Day", shapeBy = "replicate", add.labels = FALSE)
# 
# orca(p, file = "Figure_Output/Exploratory/Proteomics_PCA.png")
# orca(p, file = "Figure_Output/Exploratory/Proteomics_PCA.pdf")
```


```{r}
show_col(pal_uchicago())
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[4],pal_uchicago("default")(9)[5],pal_uchicago("default")(9)[6],pal_uchicago("default")(9)[9])


#assay
x <- assays(se)$imputed

#preparation
x <- t(x[which(!(apply(x, 1, var) == 0)), ])
pca <- prcomp(x)

#annotation
samples_data = as.data.frame(colData(se))
annotation_columns = colnames(colData(se))

samples_data <- samples_data[row.names(pca$x), ]
samples_data$names <- row.names(samples_data)
labs <- annotation_columns
labs[which(labs == "names")] <- ""
text <- apply(samples_data[, annotation_columns, drop = F], 
                  1, labs = labs, FUN = function(x, labs) {
                    paste(paste(labs, x), collapse = "\n")
                  })

#annotation
colorBy = "Day"
shapeBy = "experiment"

cb <- samples_data[, colorBy]
if (is.numeric(cb)) cb <- as.character(cb)

sb <- samples_data[, shapeBy]
if (is.numeric(sb)) sb <- as.factor(as.character(sb))


#plot components
xlab <- paste("PC ", "1", " (", round(pca$sdev[1]/sum(pca$sdev) *
                                                       100, 0), "%)", sep = "")
ylab <- paste("PC ", "2", " (", round(pca$sdev[2]/sum(pca$sdev) *
                                                       100, 0), "%)", sep = "")

df <- data.frame(x = pca$x[,1],y = pca$x[,2])

p1 <- ggplot(df, aes(x = x, y = y)) +
  geom_hline(yintercept=0, linewidth = 0.25) +
  geom_vline(xintercept=0, linewidth = 0.25) +
  geom_point(aes(color = cb, shape = sb),size = 3) +
  theme_classic() +
  xlab(xlab) + ylab(ylab) + 
  scale_color_manual(values = col_vec) +
  theme(text = element_text(size = 14), 
        axis.text.x = element_text(size = rel(1)),
        axis.text.y = element_text(size = rel(1))) +
  guides(color=guide_legend(title="Day"),shape=guide_legend(title="Differentiation"))
  

  ggsave("./Figure_Output/Exploratory/PCA_man.png",p1, width = 6.5,height = 4.5, bg = "white")

```










## Number of Proteins

```{r}
ancols <- c("Day 0"="#3F3F3F",
                       "Day 9" ="#575757",
                       "Day 15" ="#707070",
                       "Day 21" = "#898989",
                       "Day 27" ="#A1A1A1",
                       "Day 33" ="#BABABA",
                       "Day 40" = "#D3D3D3" 
)
```


```{r}
numbers_info <- assay(se) %>% data.frame() %>% rownames_to_column() %>% 
        gather(ID, bin, -rowname) %>% mutate(bin = ifelse(is.na(bin), 
        0, 1))

numbers <- numbers_info %>% group_by(ID) %>% summarize(n = n(), sum = sum(bin)) %>% 
        left_join(., data.frame(colData(se)), by = "ID")

numbers$replicate2 <- paste0("(",numbers$replicate,")")

numbers$sample <- paste0(numbers$Day," ",numbers$replicate2)

p1 <- ggplot(numbers, aes(x = sample, y = sum, fill = Day)) + 
        geom_col() + geom_hline(yintercept = unique(numbers$n)) + 
        labs(title = "Proteins per sample", x = "", y = "Number of proteins") + 
        theme_classic() + scale_fill_manual(values = ancols) + theme(
          axis.text.x = element_text(size = rel(0.85), angle = 90, vjust = 0.5, hjust=1),
          text = element_text(size = 14)
        )

ggsave("./Figure_Output/Exploratory/NumberDetectedProteins.png",p1, width = 7,height = 4.5, bg = "white")
```






