---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(ggnewscale)
})
```


```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c("darkgrey","black","lightgrey","darkgrey")
col_vec2 <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```

```{r}
#show_col(pal_uchicago("default")(9))
col_vec3 <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5],"darkgrey","black","lightgrey","darkgrey")
```



```{r}
norm_to <- function(df,norm_to){
  nn <- df[df$Condition == norm_to,]
  nn$Condition <- NULL
  name <- paste0("Norm_",norm_to)
  colnames(nn)[colnames(nn) == "x"] <- name
  df <- merge(df,nn, by = c("Day","Differentiation"))
  df$Normalized <- df$x / df[[name]]
  df <- df[df$Condition != norm_to,]
}
```


#Load Data
```{r}
e <- readRDS("./DataPrep/Neurite_Result_pLNA_SingleSoma.rds")
e <- e[e$Day != "Day27",]
e$Day <- droplevels(e$Day)
e <- e[e$Condition != "pLNA-3943",]
e$Condition <- droplevels(e$Condition)
```


```{r}
e$isEmpty <- ifelse(e$Condition == "Empty","p5","p6")
e$isEmpty2 <- ifelse(e$Condition == "Empty","p7","p8")


e21 <- e[e$Day == "Day21",]
e33 <- e[e$Day == "Day33",]
```

#Aggregate Means
```{r}
ag_le <- aggregate(log1p(e$TotalLength_um),e[,c("Day","Differentiation","Condition")], FUN=mean)
ag_le$isEmpty <- ifelse(ag_le$Condition == "Empty","p5","p6")
ag_le$isEmpty2 <- ifelse(ag_le$Condition == "Empty","p7","p8")
ag_le21 <- ag_le[ag_le$Day == "Day21",]
ag_le33 <- ag_le[ag_le$Day == "Day33",]

ag_br <- aggregate(e$NumberBranchEnds,e[,c("Day","Differentiation","Condition")], FUN=mean)
ag_br$isEmpty <- ifelse(ag_br$Condition == "Empty","p5","p6")
ag_br$isEmpty2 <- ifelse(ag_br$Condition == "Empty","p7","p8")
ag_br21 <- ag_br[ag_br$Day == "Day21",]
ag_br33 <- ag_br[ag_br$Day == "Day33",]

ag_se <- aggregate(e$NumberNonTrunkBranches,e[,c("Day","Differentiation","Condition")], FUN=mean)
ag_se$isEmpty <- ifelse(ag_se$Condition == "Empty","p5","p6")
ag_se$isEmpty2 <- ifelse(ag_se$Condition == "Empty","p7","p8")
ag_se21 <- ag_se[ag_se$Day == "Day21",]
ag_se33 <- ag_se[ag_se$Day == "Day33",]
```




##################
##################
#Length

## Means

#get statistics
```{r}
st_df_mea_le <- readRDS("./stats/ST_DF_Length_means.rds")
st_df_mea_le <- st_df_mea_le[st_df_mea_le$group2 != "pLNA-3943",]
```


```{r}
#add y_position
y_pos <- c()
for(i in st_df_mea_le$Day) {
  ll <- max(ag_le[ag_le$Day == i,"x"])
  y_pos <- c(y_pos,ll)
}

st_df_mea_le$y_pos <- y_pos*1.025
st_df_mea_le$y_adj <- rep(c(0,0,3.25,0))
st_df_mea_le$y_pos2 <- st_df_mea_le$y_pos + st_df_mea_le$y_adj

st_df_mea_le$p.value.signif[st_df_mea_le$p.value.signif == "ns"] <- NA
st_df_mea_le$p.value.signif[st_df_mea_le$p.value < 0.25] <- round(st_df_mea_le$p.value[st_df_mea_le$p.value < 0.25],2)
```



#Length all points with statistics from means

```{r}
p1 <- ggplot(e,aes(x = Condition, y = log1p(TotalLength_um))) + 
  geom_violin(aes(colour = isEmpty2),show.legend = FALSE) +
  stat_summary(
    aes(color = isEmpty),
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  scale_color_manual(values = col_vec,guide = "none") +
  new_scale_color() +
  stat_summary(aes(color = Differentiation, alpha = isEmpty),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  scale_alpha_discrete(range = c(0.3, 0.6), guide = "none") +
  scale_color_manual(values = col_vec2) +
  ggsignif::geom_signif(
    data = st_df_mea_le,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos2),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  facet_wrap(~ Day) +
  ylab("Dendrite Length in µm (log)") +
  theme_classic(base_size = 12)+
  coord_cartesian(ylim = c(0,7)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        legend.title = element_text(size = 16,margin = margin(0,20,0,0)),
        legend.text = element_text(size = 16),
        legend.position = "bottom") +
  scale_x_discrete(labels=c("Empty","pLNA-\nCtrl","pLNA-\n1229","pLNA-\n181c"))


gt1 <- ggplotGrob(p1)


panels = subset(gt1$layout, grepl("panel", gt1$layout$name), t:r)

# The span of the vertical gap
Bmin = min(panels$t) - 1
Bmax = max(panels$t)

# The columns of the gaps (two to the right of the panels
cols = unique(panels$r)[-length(unique(panels$r))] + 2

# The grob
g1 <- linesGrob(x = unit(c(.5, .5), "npc"),
              y = unit(c(0.01,0.94), "npc"),
              gp = gpar(col = "black", lty = "dotted", lwd = 1.5) )


## Add lines into the vertical gaps
gt1 <- gtable_add_grob(gt1, 
      rep(list(g1), length(cols)),
      t=Bmin, l = cols, b=Bmax)

## Draw it
grid.newpage()
grid.draw(gt1)


ggsave2("../Figures/pLNA_Length.png",gt1, width = 8,height = 6, bg = "white")
```



##################
##################
#BranchEnds

## Means

#get statistics
```{r}
st_df_mea_br <- readRDS("./stats/ST_DF_BranchEnds_means.rds")
st_df_mea_br <- st_df_mea_br[st_df_mea_br$group2 != "pLNA-3943",]
```


```{r}
#add y_position
y_pos <- c()
for(i in st_df_mea_br$Day) {
  ll <- mean(sqrt(e[e$Day == i,"NumberBranchEnds"]))
  y_pos <- c(y_pos,ll)
}

st_df_mea_br$y_pos <- y_pos 
st_df_mea_br$y_adj <- rep(c(0,0,1.25,0))
st_df_mea_br$y_pos2 <- st_df_mea_br$y_pos + st_df_mea_br$y_adj

st_df_mea_br$p.value.signif[st_df_mea_br$p.value.signif == "ns"] <- NA
```


#On all datapoints with mean statistics
```{r}
p2 <- ggplot(e,aes(x = Condition, y= sqrt(NumberBranchEnds))) + 
  stat_summary(
    aes(color = isEmpty),
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  scale_color_manual(values = col_vec,guide = "none") +
  new_scale_color() +
  stat_summary(aes(color = Differentiation, alpha = isEmpty),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  scale_alpha_discrete(range = c(0.3, 0.6), guide = "none") +
  scale_color_manual(values = col_vec2) +
  ggsignif::geom_signif(
    data = st_df_mea_br,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos2),
    textsize = 4, vjust = -0.1, size = 0.75,tip_length = 0.005, manual = TRUE
  ) +
  #geom_point(aes(color = Differentiation),alpha = 0.6) +
  facet_wrap(~ Day) +
  ylab("Number of Branch Ends (sqrt)") +
  theme_classic(base_size = 12)+
  coord_cartesian(ylim = c(0,3.75)) +
theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        legend.title = element_text(size = 16,margin = margin(0,20,0,0)),
        legend.text = element_text(size = 16),
        legend.position = "bottom") +
  scale_x_discrete(labels=c("Empty","pLNA-\nCtrl","pLNA-\n1229","pLNA-\n181c"))


gt2 <- ggplotGrob(p2)


panels = subset(gt2$layout, grepl("panel", gt2$layout$name), t:r)

# The span of the vertical gap
Bmin = min(panels$t) - 1
Bmax = max(panels$t)

# The columns of the gaps (two to the right of the panels
cols = unique(panels$r)[-length(unique(panels$r))] + 2

# The grob
g2 <- linesGrob(x = unit(c(.5, .5), "npc"),
              y = unit(c(0.01,0.94), "npc"),
              gp = gpar(col = "black", lty = "dotted", lwd = 1.5) )


## Add lines into the vertical gaps
gt2 <- gtable_add_grob(gt2, 
      rep(list(g2), length(cols)),
      t=Bmin, l = cols, b=Bmax)

## Draw it
grid.newpage()
grid.draw(gt2)

ggsave2("../Figures/pLNA_BranchEnds.png",gt2, width = 8,height = 6, bg = "white")
```








##################
##################
#Number Secondary Branches

## Means

#get statistics
```{r}
st_df_mea_se <- readRDS("./stats/ST_DF_SecondaryBranches_means.rds")
st_df_mea_se <- st_df_mea_se[st_df_mea_se$group2 != "pLNA-3943",]
```


```{r}
#add y_position
y_pos <- c()
for(i in st_df_mea_se$Day) {
  ll <- mean(sqrt(e[e$Day == i,"NumberNonTrunkBranches"]))
  y_pos <- c(y_pos,ll)
}

st_df_mea_se$y_pos <- y_pos*1.05
st_df_mea_se$y_adj <- rep(c(0,0,2,0))
st_df_mea_se$y_pos2 <- st_df_mea_se$y_pos + st_df_mea_se$y_adj
st_df_mea_se$p.value.signif[st_df_mea_se$p.value < 0.1 & st_df_mea_se$p.value > 0.05] <- round(st_df_mea_se$p.value[st_df_mea_se$p.value < 0.15 & st_df_mea_se$p.value > 0.05],2)
st_df_mea_se$p.value.signif[st_df_mea_se$p.value.signif == "ns"] <- NA
```


#On all datapoints with mean statistics
```{r}
p3 <- ggplot(e,aes(x = Condition, y= sqrt(NumberNonTrunkBranches))) + 
  stat_summary(
    aes(color = isEmpty),
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  scale_color_manual(values = col_vec,guide = "none") +
  new_scale_color() +
  stat_summary(aes(color = Differentiation, alpha = isEmpty),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  scale_alpha_discrete(range = c(0.3, 0.6), guide = "none") +
  scale_color_manual(values = col_vec2) +
  ggsignif::geom_signif(
    data = st_df_mea_se,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos2),
    textsize = 4, vjust = -0.1, size = 0.75,tip_length = 0.005, manual = TRUE
  ) +
  #geom_point(aes(color = Differentiation),alpha = 0.6) +
  facet_wrap(~ Day) +
  ylab("Number of Secondary Branches (sqrt)") +
  theme_classic()+
  coord_cartesian(ylim = c(0,4.75)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        legend.title = element_text(size = 16,margin = margin(0,20,0,0)),
        legend.text = element_text(size = 16),
        legend.position = "bottom") +
  scale_x_discrete(labels=c("Empty","pLNA-\nCtrl","pLNA-\n1229","pLNA-\n181c"))


gt3 <- ggplotGrob(p3)


panels = subset(gt3$layout, grepl("panel", gt3$layout$name), t:r)

# The span of the vertical gap
Bmin = min(panels$t) - 1
Bmax = max(panels$t)

# The columns of the gaps (two to the right of the panels
cols = unique(panels$r)[-length(unique(panels$r))] + 2

# The grob
g3 <- linesGrob(x = unit(c(.5, .5), "npc"),
              y = unit(c(0.01,0.94), "npc"),
              gp = gpar(col = "black", lty = "dotted", lwd = 1.5) )


## Add lines into the vertical gaps
gt3 <- gtable_add_grob(gt3, 
      rep(list(g3), length(cols)),
      t=Bmin, l = cols, b=Bmax)

## Draw it
grid.newpage()
grid.draw(gt3)

ggsave2("../Figures/pLNA_SecBranches.png",gt3, width = 8,height = 5, bg = "white")
ggsave2("../Figures/pLNA_SecBranches.pdf",gt3, width = 8,height = 5, bg = "white")
```

```{r}
#Source data Fig. 3f)
write.csv(e,file = "../../../../../12_SourceData/Fig3/Fig_3f.csv")
```



#Normalized to control
```{r}
ag_se_norm <- norm_to(ag_se,"pLNA-Ctrl")

p4 <- ggplot(ag_se_norm, aes(x = Condition, y = Normalized)) +
  geom_bar(stat = "summary", fun = "mean", aes(colour = isEmpty2.x),
           fill = "white", linewidth = 1, show.legend = FALSE) +
  scale_color_manual(values = col_vec,guide = "none") +
  new_scale_color() +
  geom_point(aes(colour = Differentiation, alpha = isEmpty.x), 
             size = 2, show.legend = TRUE) +
  scale_color_manual(values = col_vec2) +
  scale_alpha_discrete(range = c(0.3, 0.6),guide = "none") +
  facet_wrap(~ Day) +
  ylab("Secondary Branches (Norm. to Ctrl.)") +
  geom_hline(yintercept = 1,linetype = "dashed") +
  theme_classic(base_size = 12)+
  #coord_cartesian(ylim = c(NA,10)) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        legend.title = element_text(size = 16,margin = margin(0,20,0,0)),
        legend.text = element_text(size = 16),
        legend.position = "bottom") +
  scale_x_discrete(labels=c("Empty","pLNA-\n1229","pLNA-\n181c"))


gt4 <- ggplotGrob(p4)


panels = subset(gt4$layout, grepl("panel", gt4$layout$name), t:r)

# The span of the vertical gap
Bmin = min(panels$t) - 1
Bmax = max(panels$t)

# The columns of the gaps (two to the right of the panels
cols = unique(panels$r)[-length(unique(panels$r))] + 2

# The grob
g4 <- linesGrob(x = unit(c(.5, .5), "npc"),
              y = unit(c(0.01,0.94), "npc"),
              gp = gpar(col = "darkgrey", lty = "dotted", lwd = 1.5) )


## Add lines into the vertical gaps
gt4 <- gtable_add_grob(gt4, 
      rep(list(g4), length(cols)),
      t=Bmin, l = cols, b=Bmax)

## Draw it
grid.newpage()
grid.draw(gt4)


ggsave("../Figures/pLNA_SecBranches_normtoCtrl.png",gt4, width = 8,height = 6, bg = "white")
```









