---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(MASS)
})
```


#Load Data

```{r}
#re00
re00 <- read.csv("../../analysis/240315_Re00/Re00_Cellprofiler/Re00_cp_out/250807_Re00_240315mito.csv") 
re00_check <- re00
re00$Diff <- "Re00"
re00$blinded_numbers <- re00$FileName_raw
re00 <- re00[,-grep("PathName",colnames(re00))]
re00 <- re00[,-grep("FileName",colnames(re00))]

re00_blind <- read.csv("../../raw/240315_Re00/blinded_numbers.csv")
re00_blind$blinded_numbers <- gsub("A_","Re00_",re00_blind$blinded_numbers)
re00 <- merge(re00,re00_blind, by = "blinded_numbers",all.x = TRUE)
re00$sample <- sapply(strsplit(re00$image,"\\_"),"[",5)
re00$sample <- gsub("control","pLNA-Ctrl",re00$sample)
re00$sample <- gsub("1229","pLNA-1229",re00$sample)
```

```{r}
#re02
re02 <- read.csv("../../analysis/240614_Re02/Re02_Cellprofiler/Re02_cp_out/250807_Re02_240614mito.csv") 
re02_check <- re02
re02$Diff <- "Re02"
re02$blinded_numbers <- re02$FileName_raw
re02 <- re02[,-grep("PathName",colnames(re02))]
re02 <- re02[,-grep("FileName",colnames(re02))]

re02_blind <- read.csv("../../raw/240614_Re02/blinded_numbers.csv")
re02_blind$blinded_numbers <- gsub("A_","Re02_",re02_blind$blinded_numbers)
re02 <- merge(re02,re02_blind, by = "blinded_numbers",all.x = TRUE)
re02$sample <- sapply(strsplit(re02$image,"\\_"),"[",5)
re02$sample <- gsub("CNTRL","pLNA-Ctrl",re02$sample)
re02$sample <- gsub("1229","pLNA-1229",re02$sample)
```


```{r}
#re03
re03 <- read.csv("../../analysis/240621_Re03/Re03_Cellprofiler/Re03_cp_out/250807_Re03_240621mito.csv") 
re03_check <- re03
re03$Diff <- "Re03"
re03$blinded_numbers <- re03$FileName_raw
re03 <- re03[,-grep("PathName",colnames(re03))]
re03 <- re03[,-grep("FileName",colnames(re03))]

re03_blind <- read.csv("../../raw/240621_Re03/blinded_numbers.csv")
re03_blind$blinded_numbers <- gsub("A_","Re03_",re03_blind$blinded_numbers)
re03 <- merge(re03,re03_blind, by = "blinded_numbers",all.x = TRUE)
re03$sample <- sapply(strsplit(re03$image,"\\_"),"[",5)
re03$sample <- gsub("CNTRL","pLNA-Ctrl",re03$sample)
re03$sample <- gsub("1229","pLNA-1229",re03$sample)
```


```{r}
#ms2
ms2 <- read.csv("../../analysis/241129_MS2/MS2_Cellprofiler/MS2_cp_out/250807_MS2_241129mito.csv")
ms2_check <- ms2
ms2$Diff <- "MS2"
ms2$blinded_numbers <- ms2$FileName_raw
ms2 <- ms2[,-grep("PathName",colnames(ms2))]
ms2 <- ms2[,-grep("FileName",colnames(ms2))]

ms2_blind <- read.csv("../../raw/241129_MS2/blinded_numbers.csv")
ms2_blind$blinded_numbers <- gsub("A_","MS2_",ms2_blind$blinded_numbers)
ms2 <- merge(ms2,ms2_blind, by = "blinded_numbers",all.x = TRUE)
ms2$sample <- sapply(strsplit(ms2$image,"\\_"),"[",4)
ms2$sample <- gsub("control","pLNA-Ctrl",ms2$sample)
ms2$sample <- gsub("1229","pLNA-1229",ms2$sample)
```


```{r}
#ms3
ms3 <- read.csv("../../analysis/241206_MS3/MS3_Cellprofiler/MS3_cp_out/250807_MS3_241206mito.csv")
ms3_check <- ms3
ms3$Diff <- "MS3"
ms3$blinded_numbers <- ms3$FileName_raw
ms3 <- ms3[,-grep("PathName",colnames(ms3))]
ms3 <- ms3[,-grep("FileName",colnames(ms3))]

ms3_blind <- read.csv("../../raw/241206_MS3/blinded_numbers.csv")
ms3_blind$blinded_numbers <- gsub("A_","MS3_",ms3_blind$blinded_numbers)
ms3 <- merge(ms3,ms3_blind, by = "blinded_numbers",all.x = TRUE)
ms3$sample <- sapply(strsplit(ms3$image,"\\_"),"[",4)
ms3$sample <- gsub("Control","pLNA-Ctrl",ms3$sample)
ms3$sample <- gsub("1229","pLNA-1229",ms3$sample)
```

#Exclude images with somas that couldn't be well found by Ilastik
Re00 
-	Re00_5
Re03
-	Re03_10
-	Re03_31
MS2
-	MS2_17

```{r}
#re00
re00 <- re00[re00$blinded_numbers != "Re00_5.tif",]

#re03
re03 <- re03[!(re03$blinded_numbers %in% c("Re03_10.tif","Re03_31.tif")),]

#ms2
ms2 <- ms2[ms2$blinded_numbers != "MS2_17.tif",]
```

#Filter out all mitos that are not in the soma and have a higher intensity than 5x the standard deviation
```{r}
#re00
re00_filter <- re00[re00$Parent_SomaEx == 0,]
re00_filter_val <- mean(re00_filter$Intensity_MeanIntensity_cropRaw) + 
  (5* sd(re00_filter$Intensity_MeanIntensity_cropRaw))
neg_re00_filter_val <- mean(re00_filter$Intensity_MeanIntensity_cropRaw) - 
  (5* sd(re00_filter$Intensity_MeanIntensity_cropRaw))

re00 <- re00[(re00$Parent_SomaEx > 0) | (re00$Parent_SomaEx == 0 & re00$Intensity_MeanIntensity_cropRaw < re00_filter_val),]
max(re00[re00$Parent_SomaEx == 0,"Intensity_MeanIntensity_cropRaw"])

#re02
re02_filter <- re02[re02$Parent_SomaEx == 0,]
re02_filter_val <- mean(re02_filter$Intensity_MeanIntensity_cropRaw) + 
  (5* sd(re02_filter$Intensity_MeanIntensity_cropRaw))
neg_re02_filter_val <- mean(re02_filter$Intensity_MeanIntensity_cropRaw) - 
  (5* sd(re02_filter$Intensity_MeanIntensity_cropRaw))

re02 <- re02[(re02$Parent_SomaEx > 0) | (re02$Parent_SomaEx == 0 & re02$Intensity_MeanIntensity_cropRaw < re02_filter_val),]
max(re02[re02$Parent_SomaEx == 0,"Intensity_MeanIntensity_cropRaw"])

#re03
re03_filter <- re03[re03$Parent_SomaEx == 0,]
re03_filter_val <- mean(re03_filter$Intensity_MeanIntensity_cropRaw) + 
  (5* sd(re03_filter$Intensity_MeanIntensity_cropRaw))
neg_re03_filter_val <- mean(re03_filter$Intensity_MeanIntensity_cropRaw) - 
  (5* sd(re03_filter$Intensity_MeanIntensity_cropRaw))

re03 <- re03[(re03$Parent_SomaEx > 0) | (re03$Parent_SomaEx == 0 & re03$Intensity_MeanIntensity_cropRaw < re03_filter_val),]
max(re03[re03$Parent_SomaEx == 0,"Intensity_MeanIntensity_cropRaw"])

#ms2
ms2_filter <- ms2[ms2$Parent_SomaEx == 0,]
ms2_filter_val <- mean(ms2_filter$Intensity_MeanIntensity_cropRaw) + 
  (5* sd(ms2_filter$Intensity_MeanIntensity_cropRaw))
neg_ms2_filter_val <- mean(ms2_filter$Intensity_MeanIntensity_cropRaw) - 
  (5* sd(ms2_filter$Intensity_MeanIntensity_cropRaw))

ms2 <- ms2[(ms2$Parent_SomaEx > 0) | (ms2$Parent_SomaEx == 0 & ms2$Intensity_MeanIntensity_cropRaw < ms2_filter_val),]
max(ms2[ms2$Parent_SomaEx == 0,"Intensity_MeanIntensity_cropRaw"])

#ms3
ms3_filter <- ms3[ms3$Parent_SomaEx == 0,]
ms3_filter_val <- mean(ms3_filter$Intensity_MeanIntensity_cropRaw) + 
  (5* sd(ms3_filter$Intensity_MeanIntensity_cropRaw))
neg_ms3_filter_val <- mean(ms3_filter$Intensity_MeanIntensity_cropRaw) - 
  (5* sd(ms3_filter$Intensity_MeanIntensity_cropRaw))

ms3 <- ms3[(ms3$Parent_SomaEx > 0) | (ms3$Parent_SomaEx == 0 & ms3$Intensity_MeanIntensity_cropRaw < ms3_filter_val),]
max(ms3[ms3$Parent_SomaEx == 0,"Intensity_MeanIntensity_cropRaw"])
```


```{r}
e <- rbind(re00,re02,re03,ms2,ms3)
e$sample <- factor(e$sample,levels = c("pLNA-Ctrl","pLNA-1229","TSB"))
e$Diff <- factor(e$Diff)
```

```{r}
e <- e[e$sample != "TSB",]
e$sample <- droplevels(e$sample)
```


```{r}
replacement <- c(Re00 = "r4",Re02 = "r6",Re03 = "r7",MS2 = "r2", MS3 = "r3")
e$Diff <- replacement[as.character(e$Diff)]
e$Diff <- factor(e$Diff,levels = c("r2","r3","r4","r6","r7"))
```

```{r}
saveRDS(e,"../data/TMRE_Data.rds")
```








```{r}
#check whether all names are correct
check <- rbind(re00_check,re02_check,re03_check,ms2_check,ms3_check)
check <- check[,grep("FileName",colnames(check))]
check$FileName_mito <- gsub("Probabilities_0_","",check$FileName_mito)
check$FileName_soma <- gsub("Probabilities_0_","",check$FileName_soma)

check$correct_name <- apply(check[,colnames(check)], 1, function(row) length(unique(row)) == 1)
all(check$correct_name == "TRUE")
```









