---
title: "CaImaging"
author: "Michael"
date: '2022-10-17'
output: html_document
---                                                                                                              


#libraries
```{r}
suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(stringr)
  library(reshape2)
  library(emmeans)
  library(ggrepel)
  library(emmeans)
  library(dplyr)
  library(cowplot)
  library(viridis)
  library(ggsci)
  library(MASS)
  library(rstatix)
  library(ggsignif)
  library(grid)
  library(gtable)
  library(lme4)
  library(stats)
  library(performance)
})
```



```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```


#get Data
```{r}
res <- readRDS("./PeakTable_075.rds")
res$Condition <- factor(res$Condition, levels = c("pLNA-Ctrl_MC","pLNA-1229_MC","pLNA-Ctrl_MA","pLNA-1229_MA"))
```

```{r}
res$Differentiation <- tolower(res$Differentiation)
res$Differentiation <- factor(res$Differentiation,levels = c("m1","m2","m3"))
```

```{r}
res$pLNA <- res$LNA
res$DishID <- with(res, interaction(Differentiation, Drug, pLNA, CVS, drop = TRUE))
res$VideoID <- with(res, interaction(DishID, Video, drop=TRUE))
res$CellID <- with(res, interaction(VideoID, Cell.Trace, drop=TRUE))
```

```{r}
res$pLNA <- factor(res$pLNA,levels = c("pLNA-Ctrl","pLNA-1229"))
res$Drug <- factor(res$Drug,levels = c("MC","MA"))
```

```{r}
ls <- c("Mitochondria ctrl.","Mitochondrial activation")
names(ls) <- c("MC","MA")
```


# get cell info
```{r}
cell_info <- unique(res[, c("Day","CellID","Condition","VideoID","DishID","Differentiation","Drug","pLNA")])
```


######################
######################
##Amplitude

##Preparation
```{r}
e <- aggregate(
   cbind(log_amp_mean = log(Peak.Intensity.df.F.),amp_mean = Peak.Intensity.df.F.) 
   ~ Day + Differentiation + Condition + Drug + pLNA + DishID + VideoID + CellID,
  data = res,
  FUN  = mean
)
```

```{r}
#Get cell numbers
NumSpikesCond <- aggregate(res$Peak.Intensity.df.F.,res[,c("Condition"),drop = FALSE],FUN = length)

NumCellsCond <- aggregate(e$CellID,e[,c("Condition"),drop = FALSE],FUN = length)
NumCellsCond$pLNA <- sapply(strsplit(as.character(NumCellsCond$Condition),"_"),"[",1)
NumCellsCond$pLNA <- factor(NumCellsCond$pLNA,levels = c("pLNA-Ctrl","pLNA-1229"))
NumCellsCond$Drug <- sapply(strsplit(as.character(NumCellsCond$Condition),"_"),"[",2)
NumCellsCond$Drug <- factor(NumCellsCond$Drug,levels = c("MC","MA"))
```



```{r}
# Test for Intraclass Correlation Coefficient (ICC)
icc_amp <- lmer(log_amp_mean ~ pLNA * Drug + Differentiation + (1 | DishID), data = e)
vc <- VarCorr(icc_amp)
var_dish <- as.numeric(vc$DishID)
var_res  <- attr(vc, "sc")^2
ICC <- var_dish / (var_dish + var_res)
ICC

#with package performance
icc(icc_amp)
```
# ICC of about ~22%, perform statistic on cellular level


#Amplitude Plot
```{r}
mod_s1 <- lm(log_amp_mean ~ pLNA*Drug + Differentiation, data = e)
s1 <- emmeans(mod_s1, pairwise ~ pLNA|Drug)

s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "pLNA-Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\(pLNA-Ctrl\\) - \\(","",s1_df$group2)
s1_df$group2 <- gsub("\\)", "",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")
#s1_df$p.value.signif <- round(s1_df$p.value,3)


#add y_position
y_pos <- c()
for(i in levels(factor(e$Drug))) {
  ll <- max(e[e$Drug == i,"log_amp_mean"])
  y_pos <- c(y_pos,ll)
}

s1_df$y_pos <- y_pos + 0.15
```


```{r}
#aggregated by cell mean
p2 <- ggplot(e, aes(pLNA, log_amp_mean)) +
 geom_violin(colour = "grey") +
  stat_summary(
    fun = mean,
    geom="crossbar"
  ) +
  stat_summary(aes(color = Differentiation),
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35),alpha = 0.6, size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE,
  ) +
  facet_wrap(~ Drug, labeller = labeller(Drug = ls)) +
  geom_label(data = NumCellsCond, mapping=aes(x=pLNA, y=-2.9, label= x)) +
  annotate("text", label = "#Cells:",x = 1, y = -2.75, ) +
  ylab("Ca-Amplitude (log)") +
  scale_color_manual(values = col_vec) +
  theme_classic() +
  coord_cartesian(ylim = c(NA,-0.15))+
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))  +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figures/CaImaging_Amplitude_overview_cell.pdf",p2, width = 7.25,height = 5)
```

```{r}
#Source data Fig. 5i)
write.csv(e,"../../../12_SourceData/Fig5/Fig_5i.csv")
```



######################
######################
##Frequency


##Preparation

```{r}
peak_count <- aggregate(Peak.Intensity.df.F. ~ CellID, data = res, FUN = length)
names(peak_count)[2] <- "spikes"

f <- merge(peak_count, cell_info, by = "CellID", all.x = TRUE)

f$Recording_s   <- 270
f$Recording_min <- f$Recording_s / 60

f$Freq <- f$spikes / f$Recording_s
```


```{r}
# Test for Intraclass Correlation Coefficient (ICC)
icc_freq <- lmer(Freq ~ pLNA * Drug + Differentiation + (1 | DishID), data = f)
vc <- VarCorr(icc_freq)
var_dish <- as.numeric(vc$DishID)
var_res  <- attr(vc, "sc")^2
ICC <- var_dish / (var_dish + var_res)
ICC

#with package performance
icc(icc_freq)
```

# ICC of about ~24%, perform statistic on cellular level

#Frequency Plot
```{r}
mod_s2 <- lm(Freq ~ pLNA*Drug + Differentiation, data = f)
s2 <- emmeans(mod_s2, pairwise ~ pLNA|Drug)

s2_df <- as.data.frame(s2$contrasts)
s2_df$group1 <- "pLNA-Ctrl"
s2_df$group2 <- s2_df$contrast
s2_df$group2 <- gsub("\\(pLNA-Ctrl\\) - \\(","",s2_df$group2)
s2_df$group2 <- gsub("\\)", "",s2_df$group2)
s2_df <- add_significance(s2_df,p.col = "p.value")
# s2_df$p.value.signif <- round(s2_df$p.value,2)

#add y_position
y_pos <- c()
for(i in levels(factor(f$Drug))) {
  ll <- max(f[f$Drug == i,"Freq"])
  y_pos <- c(y_pos,ll)
}

s2_df$y_pos <- y_pos*1.1
```


```{r}
#aggregated per cell
p_f <- ggplot(f, aes(pLNA, Freq)) +
 geom_violin(colour = "grey") +
  stat_summary(
    fun = mean,
    geom="crossbar"
  ) +
  stat_summary(aes(color = Differentiation),
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35),alpha = 0.6, size = 0.75
  ) +
  #geom_point(aes(color = Differentiation),alpha = 0.4,position=position_dodge(width=0.35)) +
  ggsignif::geom_signif(
    data = s2_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE,
  ) +
  facet_wrap(~ Drug, labeller = labeller(Drug = ls)) +
  geom_label(data = NumCellsCond, mapping=aes(x=pLNA, y=-0.01, label= x)) +
  annotate("text", label = "#Cells:",x = 1, y = 0.00, ) +
  ylab("Spike frequency of ind. cells [hz]") +
  scale_color_manual(values = col_vec) +
  theme_classic(base_size = 13) +
  coord_cartesian(ylim = c(NA,0.1525))+
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))  +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figures/CaImaging_Frequency_overview_cell.pdf",p_f, width = 7.5,height = 5)
```
```{r}
#Source data Fig. 5j)
write.csv(f,"../../../12_SourceData/Fig5/Fig_5j.csv")
```





######################
######################

## Add Peak Duration


##Preparation
```{r}
g <- aggregate(
   Peak.Duration.s. ~ Day + Differentiation + Condition + Drug + pLNA + DishID + VideoID + CellID,
  data = res,
  FUN  = mean
)

colnames(g)[which(colnames(g) == "Peak.Duration.s.")] <- "Duration"
```

```{r}
# Test for Intraclass Correlation Coefficient (ICC)
icc_duration <- lmer(Duration ~ pLNA * Drug + Differentiation + (1 | DishID), data = g)
vc <- VarCorr(icc_duration)
var_dish <- as.numeric(vc$DishID)
var_res  <- attr(vc, "sc")^2
ICC <- var_dish / (var_dish + var_res)
ICC

#with package performance
icc(icc_duration)
```

# ICC of about ~13%, perform statistic on cellular level



#Overview Peak Duration
```{r}
#aggregated
mod_s3 <- lm(sqrt(Duration) ~ pLNA*Drug + Differentiation, data = g)
s3 <- emmeans(mod_s3, pairwise ~ pLNA|Drug)

s3_df <- as.data.frame(s3$contrasts)
s3_df$group1 <- "pLNA-Ctrl"
s3_df$group2 <- s3_df$contrast
s3_df$group2 <- gsub("\\(pLNA-Ctrl\\) - \\(","",s3_df$group2)
s3_df$group2 <- gsub("\\)", "",s3_df$group2)
s3_df <- add_significance(s3_df,p.col = "p.value")
#s3_df$p.value.signif <- round(s3_df$p.value,3)

#add y_position
y_pos <- c()
for(i in levels(factor(g$Drug))) {
  ll <- sqrt(max(g[g$Drug == i,"Duration"]))
  y_pos <- c(y_pos,ll)
}

s3_df$y_pos <- y_pos*1.05
```


```{r}
#aggregated by cell mean
p4 <- ggplot(g, aes(pLNA, sqrt(Duration))) +
 geom_violin(colour = "grey") +
  stat_summary(
    fun = mean,
    geom="crossbar"
  ) +
  stat_summary(aes(color = Differentiation),
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35),alpha = 0.6, size = 0.75
  ) +
  # geom_point(aes(color = Differentiation),alpha = 0.4,position=position_dodge(width=0.35)) +
  ggsignif::geom_signif(
    data = s3_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE,
  ) +
  facet_wrap(~ Drug, labeller = labeller(Drug = ls)) +
  geom_label(data = NumCellsCond, mapping=aes(x=pLNA, y=0.5, label= x)) +
  annotate("text", label = "#Cells:",x = 1, y = 0.65) +
  ylab("Peak duration in ind. cells (sqrt)") +
  scale_color_manual(values = col_vec) +
  theme_classic(base_size = 13) +
  coord_cartesian(ylim = c(NA,2.75))+
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))  +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

ggsave2("../Figures/CaImaging_PeakDuration_cellmean.png",p4, width = 7.5,height = 5)
```






