---
title: "SeqIdentity"
author: "Michael Soutschek"
date: "4/17/2021"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(pheatmap)
  library(ggpubr)
  library(tidyverse)
  library(dplyr)
  library(viridis)
  library(ggsci)
  library(circlize)
  library(ComplexHeatmap)
})
```

# Color Definitions
```{r}
ancols <- list(day=c("0"="#3F3F3F",
                       "9" ="#575757",
                       "15" ="#707070",
                       "21" = "#898989",
                       "27" ="#A1A1A1",
                       "33" ="#BABABA",
                       "40" = "#D3D3D3" 
) )

heatcol = inferno(256)
```

```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```

#Prepare data
```{r}
## load sequence identity data
df_seqid <- readRDS("../res/seq_identity.rds")
```

# expressed MiRs
```{r}
se <- readRDS("../../../TimeCourse_GRCh38.p10_Ens91/data/Small_RNA/smallRNA_oasis.DEA.SE.rds")
se$day <- as.factor(se$day)
```

```{r}
##This works somehow only on my computer, maybe there was an update on the server packages

## associate expression miRNAs with precursors
grl <- rtracklayer::import("../data/mirnas/hsa.gff3")

smallRNA_counts <- se  %>%
  assays() %>%
  `[[`("logcpm") %>%
  as.data.frame() %>%
  rownames_to_column(var = "ID") %>%
  pivot_longer(cols = starts_with("SC")) %>%
  group_by(ID) %>%
  summarize(
    min_exp = min(value),
    max_exp = max(value),
    mean_exp = mean(value),
    median_exp = median(value)) %>%
  inner_join(mcols(grl)[c("Name", "Derives_from")], by = c("ID" = "Name"), copy=TRUE) %>%
  left_join(mcols(grl)[c("Name", "ID")], by = c("Derives_from" = "ID"), copy=TRUE) %>%
  dplyr::select(-Derives_from) %>%
  rename(precursor = Name)

length(unique(smallRNA_counts$precursor))
```

```{r}
## add human column
df_seqid <- df_seqid %>%
  mutate(human = 100)

df_seqid_exp <- df_seqid[df_seqid$miRNA %in% smallRNA_counts$precursor,]

##why is there only 375 seqid_exp?? >> it's the number of unique precursors

## only expressed miRNAs
clust_matrix_id_expressed <- df_seqid %>%
  dplyr::filter(miRNA %in% smallRNA_counts$precursor) %>%
  dplyr::select(chimpanzee:human) %>%
  as.matrix()

callback = function(hc, mat){
  sv = svd(t(mat))$v[,1]
  dend = reorder(as.dendrogram(hc), wts = sv)
  as.hclust(dend)
}
```




# set colors
```{r}
#show_col(inferno(252))

darkviolet <- "#1B0C42"
violet <- "#A52C60"
yellow <- "#FB9A06"
yellow2 <- inferno(256)[256]


ramp1 <- colorRampPalette(c(darkviolet,darkviolet))(0.6*100)
ramp2 <- colorRampPalette(inferno(256,begin = 0, end = 0.85))(0.4*100)

colors <- c(ramp1, ramp2)
```



#Plot

```{r}
e <- clust_matrix_id_expressed

colors <- circlize::colorRamp2(breaks=c(0,seq(from=60,to=99.9,length.out=254),100), inferno(256,begin = 0.1, end = 0.85))

png("./Figure_Output/sequence_identity_expMiRs_transpose_ComplexHeatmap.png", width=7, height=5, units = "in", res=300)
draw(
  Heatmap(t(e), col = colors, column_title  = "Homology to Human microRNA precursors",name = "% homology", show_column_dend = FALSE, heatmap_legend_param = list(
        at = c(0,30,60,80,100), 
        labels = c("","not conserved", "60%", "80%","100%")
    )))
dev.off()
```









