---
title: "smallRNA_SynCo_DEA"
author: "Michael Soutschek"
date: "14 1 2021"
output: html_document
---



```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(scales)
  library(ggplot2)
  library(ggsci)
  library(cowplot)
  library(ggrepel)
  library(ggnewscale)
  library(sechm)
})
```




#Load Data
```{r}
se.syn <- readRDS("../../data/Small_RNA/smallRNA_oasis.DEA.SynCoClust_Shift_normcell.SE.rds")
res <- as.data.frame(rowData(se.syn)$DEA.SynCoCluster_Shift)

se <- readRDS("../../data/Small_RNA/smallRNA_oasis_noRound.DEA.SE.rds")
se$day <- as.factor(se$day)
```

# Quick Analysis
```{r}
res.cpm2 <- res

#Don't filter futher since the max expression is for all miRs above 2
# smallRNA_counts <- se  %>%
#   assays() %>%
#   `[[`("logcpm") %>%
#   as.data.frame() %>%
#   rownames_to_column(var = "ID") %>%
#   pivot_longer(cols = starts_with("SC")) %>%
#   group_by(ID) %>%
#   summarize(
#     min_exp = min(value),
#     max_exp = max(value),
#     mean_exp = mean(value),
#     median_exp = median(value)) %>%
#   inner_join(mcols(grl)[c("Name", "Derives_from")], by = c("ID" = "Name"), copy=TRUE) %>%
#   left_join(mcols(grl)[c("Name", "ID")], by = c("Derives_from" = "ID"), copy=TRUE) %>%
#   dplyr::select(-Derives_from) %>%
#   rename(precursor = Name)


res.cpm2.mir <- res.cpm2[grep("hsa-",row.names(res.cpm2)),]

top10.mir <- row.names(head(res.cpm2.mir[order(res.cpm2.mir$FDR),],10))
res.cpm2.mir.down <- res.cpm2.mir[res.cpm2.mir$logFC < 0,]
top10.mir.down <- row.names(head(res.cpm2.mir.down[order(res.cpm2.mir.down$FDR),],10))
```



# Heatmap colors
```{r}
heatcol = inferno(256)


ancols <- list(day = c("0"="#3F3F3F",
                      "9" ="#575757",
                      "15" ="#707070",
                      "21" = "#898989",
                      "27" ="#A1A1A1",
                      "33" ="#BABABA",
                      "40" = "#D3D3D3" 
                      ) )

```



# Top 10
```{r}
# top 10 candidates neuronal
sechm(se, top10.mir, top_annotation=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols, sortRowsOn = NULL, cluster_rows = FALSE )

png("Figure_Output/SynCoDea_Shift/Heat_Top10.png", width=7, height=5, units="in", res=300)
sehm(se, top10, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE, sortRowsOn = NULL, cluster_rows = FALSE )
dev.off()
```

# Top 10 - Down
```{r}
# top 10 candidates neuronal
sechm(se, top10.mir.down, top_annotation=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols, sortRowsOn = NULL, cluster_rows = FALSE )

png("Figure_Output/SynCoDea_Shift/Heat_Top10_Down_Mir.png", width=7, height=5, units="in", res=300)
sehm(se, top10.down.mir, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE, sortRowsOn = NULL, cluster_rows = FALSE )
dev.off()
```








# Volcano

# set colors
```{r}
#show_col(pal_uchicago("default")(3))
red <- pal_uchicago("default")(3)[1]
grey <- pal_uchicago("default")(3)[2]
yellow <- pal_uchicago("default")(3)[3]
```

```{r}
#source("../../functions/plotVolcano.R")
```



# plotVolcano Function
```{r}
plotVolcano <- function(df,sig = 0.05, text.size = 20, log.base = exp(1), anno,
                        xlim_min = -5, xlim_max = 5,
                        colors = c("blue","red","grey"),
                        text_color = c("black","white"),
                        ...){

  # trans function
  reverselog_trans <- function(base = log.base) {
    trans <- function(x) -log(x, base)
    inv <- function(x) base^(-x)
    trans_new(paste0("reverselog-", format(base)), trans, inv,
              log_breaks(base = base),
              domain = c(-Inf, Inf))
  }

  if(class(df) == "DFrame") df <- as.data.frame(df)
  df$`Sign.` <- ifelse(df$FDR >= sig, "not",ifelse(df$logFC > 0,"up","down"))
  df$`Sign.` <- factor(df$`Sign.`, levels = c("up", "down", "not"))
  if(is.null(df$names)) df$names <- row.names(df)
  df$dir <- ifelse(df$logFC < 0, "downr","upr")

  # add little FDR value
  df$FDR <- ifelse(df$FDR < 1e-300,df$FDR + 1e-300,df$FDR)
  anno <- df[unlist(lapply(anno, FUN=function(x) which(df$names==x))),]

  p <- ggplot(df, aes(logFC, FDR)) +
    geom_point(aes(alpha = 0.7, color=`Sign.`)) +
    scale_color_manual(values = c("up" = colors[1],"down" = colors[2],
                                  "not" = colors[3])) +
    scale_y_continuous(trans = reverselog_trans()) +
    new_scale_color() +
    geom_label_repel(data=anno, segment.colour = "black",
                    aes(label=names),
                    show.legend = FALSE,
                    max.overlaps = 100,
                    force_pull = 1,
                    ...) +
    scale_color_manual(values = c("upr" = text_color[1],"downr"  = text_color[2])) +
    scale_fill_manual(values = c("up" = colors[1],"down" = colors[2],
                                 "not" = colors[3])) +
    xlab("log2-Fold Change") + ylab("FDR") +
    xlim(xlim_min,xlim_max) +
    theme_classic(base_size = text.size) +
    labs(alpha = NULL) +
    theme(legend.title=element_text(size=text.size-1),
          legend.text=element_text(size=text.size-3),
          axis.title =element_text(size=text.size)) +
    guides(alpha = "none")





  p
}
```


# Plot Volcano DEA
```{r}
# df prep
res.cpm2.mir <- res.cpm2[grepl("hsa-miR",row.names(res.cpm2)),]

# mirs to annotate
anno2 <- grep("-1229-3p|-4745-5|-941|-3141",row.names(res.cpm2.mir),value = TRUE)

p <- plotVolcano(df = res.cpm2.mir, text.size = 12, sig = 0.05,
                 log.base = 10,anno = anno2, 
                 xlim_min = -10,  xlim_max = 10, 
                 colors = c(yellow,red,grey),
                 text_color = c("black","white"),nudge_y = 0,  point.padding = 0,
                 box.padding = 0.5, min.segment.length = 0, force = 4)
p <- p + xlab("Similarity to morphology") +
  theme(text = element_text(size = 16), 
        axis.text.x = element_text(size = rel(1))
        )


ggsave(p,filename = "Figure_Output/SynCoDea_Shift/smallRNA_volcano.png",height = 4,width = 5)
```





