---
title: "Segmentation_Quantification"
author: "Michael Soutschek"
date: "2024-06-25"
output: html_document
---

#libraries
```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(scales)
  library(ggsci)
  library(cowplot)
  library(ggpattern)
  library(dplyr)
  library(tidyr)
  library(MASS)
  library(emmeans)
  library(ggsignif)
  library(rstatix)
})
```


```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```


```{r}
res <- readRDS("../Data/mito_res.rds")
replacement <- c(Nv11 = "n1", Nv12 = "n2", Nv13 = "n3")
res$Diff <- replacement[as.character(res$Diff)]
res$Diff <- factor(res$Diff,levels = c("n1","n2","n3"))
```



#Plot Data


## Area aggregated
```{r}
ag_area <- aggregate(res$Area_um,res[,c("Diff","Condition","ImageNumber","Compartment")], FUN=mean)
```

```{r}
mod_s1 <- lm(x ~ Condition + Diff, data = ag_area[ag_area$Compartment == "Processes",])
s1 <- emmeans(mod_s1, pairwise ~ Condition)
```

```{r}
s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("Ctrl - ","",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")
s1_df$p.value.num <- round(s1_df$p.value,3)
s1_df$p.value.signif[s1_df$p.value.signif == "ns"] <- NA

#add y_position
tt <- ag_area[ag_area$Compartment == "Processes",]
y_pos <- max(tt[,"x"])

s1_df$y_pos <- y_pos + 0.05
```


```{r}
p1 <- ggplot(aes(x = Condition, y = x), data = ag_area[ag_area$Compartment == "Processes",]) +
  geom_violin() +
  stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s1_df,
    aes(
    xmin        = group1,
    xmax        = group2,
    annotations = p.value.signif,
    y_position  = y_pos
  ),
  manual      = TRUE,
  textsize    = 4,
  vjust       = -0.1,
  size        = 0.75,
  colour      = "black"
  ) +
  ggtitle("iSIM - Day 25")+
  ylab("Mitochondrial Area in µm²") +
  theme_classic(base_size = 12) +
  coord_cartesian(ylim = c(0,0.6)) +
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))


ggsave2("../Figure_Output/Area_um_aggregated_white.png",p1, width = 5,height = 4.75, bg = "transparent")
```



## Length aggregated
```{r}
ag_length <- aggregate(res$Length_um,res[,c("Diff","Condition","ImageNumber","Compartment")], FUN=mean)
```


```{r}
mod_s2 <- lm(x ~ Condition + Diff, data = ag_length[ag_length$Compartment == "Processes",])
s2 <- emmeans(mod_s2, pairwise ~ Condition)
```

```{r}
s2_df <- as.data.frame(s2$contrasts)
s2_df$group1 <- "Ctrl"
s2_df$group2 <- s2_df$contrast
s2_df$group2 <- gsub("Ctrl - ","",s2_df$group2)
s2_df <- add_significance(s2_df,p.col = "p.value")
s2_df$p.value.num <- round(s2_df$p.value,3)
s2_df$p.value.signif[s2_df$p.value.signif == "ns"] <- NA

#add y_position
tt <- ag_length[ag_length$Compartment == "Processes",]
y_pos <- max(tt[,"x"])

s2_df$y_pos <- y_pos + 0.1
```

```{r}
p2 <- ggplot(aes(x = Condition, y = x), data = ag_length[ag_length$Compartment == "Processes",]) +
  geom_violin() +
  stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s2_df,
    aes(
    xmin        = group1,
    xmax        = group2,
    annotations = p.value.signif,
    y_position  = y_pos
  ),
  manual      = TRUE,
  textsize    = 4,
  vjust       = -0.1,
  size        = 0.75,
  colour      = "black"
  ) +
  facet_grid(~Compartment) +
  ylab("Mitochondrial Length in µm") +
  theme_classic(base_size = 18) +
  coord_cartesian(ylim = c(0,1.75)) +
  scale_color_manual(values = col_vec) +
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        )+ 
    guides(pattern = guide_legend(override.aes = list(shape = NA)),
           colour = guide_legend(override.aes = list(linetype=0,pattern_colour = "white"))
           )


ggsave2("../Figure_Output/Length_um_aggregated_white.png",p2, width = 5,height = 6, bg = "transparent")
```



## Calcium Intensity Mito aggregated
```{r}
ag_calcium_mito <- aggregate(res$Intensity_Calcium,res[,c("Diff","Condition","ImageNumber","Compartment")], FUN=mean)
```

```{r}
mod_s3 <- lm(x ~ Condition + Diff, data = ag_calcium_mito[ag_calcium_mito$Compartment == "Processes",])
s3 <- emmeans(mod_s3, pairwise ~ Condition)
```

```{r}
s3_df <- as.data.frame(s3$contrasts)
s3_df$group1 <- "Ctrl"
s3_df$group2 <- s3_df$contrast
s3_df$group2 <- gsub("Ctrl - ","",s3_df$group2)
s3_df <- add_significance(s3_df,p.col = "p.value")
s3_df$p.value.num <- round(s3_df$p.value,3)
s3_df$p.value.signif[s3_df$p.value.signif == "ns"] <- NA

#add y_position
tt <- ag_calcium_mito[ag_calcium_mito$Compartment == "Processes",]
y_pos <- max(tt[,"x"])

s3_df$y_pos <- y_pos + 0.00025
```

```{r}
p3 <- ggplot(aes(x = Condition, y = x), data = ag_calcium_mito[ag_calcium_mito$Compartment == "Processes",]) +
    geom_violin() +
  stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
    ggsignif::geom_signif(data = s3_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
    ggtitle("Processes") +
    ylab("Calcium Intensity in Mitochondria") +
    theme_classic(base_size = 12) +
    coord_cartesian(ylim = c(0.003,0.005)) +
    scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))

         

ggsave2("../Figure_Output/Calcium_aggregated_Processes.png",p3, width = 5,height = 4.75, bg = "transparent")
```







##########
#mtDNA seperated

## Area aggregated
```{r}
ag_area_1b <- aggregate(res$Area_um,res[,c("Diff","Condition","ImageNumber","mtDNA","Compartment")], FUN=mean)
```

```{r}
mod_s1b <- lm(x ~ Condition * mtDNA + Diff, data = ag_area_1b[ag_area_1b$Compartment == "Processes",])
s1b <- emmeans(mod_s1b, pairwise ~ Condition|mtDNA)
```

```{r}
s1b_df <- as.data.frame(s1b$contrasts)
s1b_df$group1 <- "Ctrl"
s1b_df$group2 <- s1b_df$contrast
s1b_df$group2 <- gsub("Ctrl - ","",s1b_df$group2)
s1b_df <- add_significance(s1b_df,p.col = "p.value")
s1b_df$p.value.num <- round(s1b_df$p.value,3)
s1b_df$p.value.signif[s1b_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- c()
for(i in levels(ag_area_1b$mtDNA)) {
  tt <- ag_area_1b[ag_area_1b$Compartment == "Processes",]
  ll <- max(tt[tt$mtDNA == i ,"x"])
  y_pos <- c(y_pos,ll)
}

s1b_df$y_pos <- y_pos + 0.05
```


```{r}
p1b <- ggplot(aes(x = Condition, y = x), data = ag_area_1b[ag_area_1b$Compartment == "Processes",]) +
  geom_violin_pattern(aes(pattern = mtDNA),
                       show.legend = TRUE,
                       linewidth = 0.5, 
                       alpha = 0.7,
                       pattern_color = c("black"),
                       fill = "white",
                       color = "black",
                       pattern_angle = 45,
                       pattern_density = 0.1,
                       pattern_spacing = 0.025,
                       pattern_key_scale_factor = 0.6,) +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      fun.max = function(x) mean(x) + sd(x),
      fun.min = function(x) mean(x) - sd(x),
      geom = "errorbar",
      position = position_dodge(width = 0.5),
      alpha = 0.7,
      size = 0.75,
      width = 0,
      show.legend = FALSE
    ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      geom = "point",
      position = position_dodge(width = 0.5),
      size = 4,   # Point size
      alpha = 0.9,
      show.legend = TRUE
    ) +
  ggsignif::geom_signif(data = s1b_df,
    aes(
    xmin        = group1,
    xmax        = group2,
    annotations = p.value.signif,
    y_position  = y_pos
  ),
  manual      = TRUE,
  textsize    = 4,
  vjust       = -0.1,
  size        = 0.75,
  colour      = "black"
  ) +
  facet_grid(Compartment ~ mtDNA) +
  ylab("Mitochondrial Area in µm²") +
  theme_classic(base_size = 18) +
  coord_cartesian(ylim = c(0,0.6)) +
  scale_color_manual(values = col_vec) +
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        )+ 
    guides(pattern = guide_legend(override.aes = list(shape = NA)),
           colour = guide_legend(override.aes = list(linetype=0,pattern_colour = "white"))
           )


ggsave2("../Figure_Output/mtDNA_Area_um_aggregated_white.png",p1b, width = 8,height = 6, bg = "transparent")
```



## Length aggregated
```{r}
ag_length_2b <- aggregate(res$Length_um,res[,c("Diff","Condition","ImageNumber","mtDNA","Compartment")], FUN=mean)
```


```{r}
mod_s2b <- lm(x ~ Condition * mtDNA + Diff, data = ag_length_2b[ag_length_2b$Compartment == "Processes",])
s2b <- emmeans(mod_s2b, pairwise ~ Condition|mtDNA)
```

```{r}
s2b_df <- as.data.frame(s2b$contrasts)
s2b_df$group1 <- "Ctrl"
s2b_df$group2 <- s2b_df$contrast
s2b_df$group2 <- gsub("Ctrl - ","",s2b_df$group2)
s2b_df <- add_significance(s2b_df,p.col = "p.value")
s2b_df$p.value.num <- round(s2b_df$p.value,3)
s2b_df$p.value.signif[s2b_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- c()
for(i in levels(ag_length_2b$mtDNA)) {
  tt <- ag_length_2b[ag_length_2b$Compartment == "Processes",]
  ll <- max(tt[tt$mtDNA == i ,"x"])
  y_pos <- c(y_pos,ll)
}

s2b_df$y_pos <- y_pos + 0.1
```

```{r}
p2b <- ggplot(aes(x = Condition, y = x), data = ag_length_2b[ag_length_2b$Compartment == "Processes",]) +
   geom_violin_pattern(aes(pattern = mtDNA),
                       show.legend = TRUE,
                       linewidth = 0.5, 
                       alpha = 0.7,
                       pattern_color = c("black"),
                       fill = "white",
                       color = "black",
                       pattern_angle = 45,
                       pattern_density = 0.1,
                       pattern_spacing = 0.025,
                       pattern_key_scale_factor = 0.6,) +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      fun.max = function(x) mean(x) + sd(x),
      fun.min = function(x) mean(x) - sd(x),
      geom = "errorbar",
      position = position_dodge(width = 0.5),
      alpha = 0.7,
      size = 0.75,
      width = 0,
      show.legend = FALSE
    ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      geom = "point",
      position = position_dodge(width = 0.5),
      size = 4,   # Point size
      alpha = 0.9,
      show.legend = TRUE
    ) +
  ggsignif::geom_signif(data = s2b_df,
    aes(
    xmin        = group1,
    xmax        = group2,
    annotations = p.value.signif,
    y_position  = y_pos
  ),
  manual      = TRUE,
  textsize    = 4,
  vjust       = -0.1,
  size        = 0.75,
  colour      = "black"
  ) +
  facet_grid(Compartment ~ mtDNA) +
  ylab("Mitochondrial Length in µm") +
  theme_classic(base_size = 18) +
  coord_cartesian(ylim = c(0,1.75)) +
  scale_color_manual(values = col_vec) +
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        )+ 
    guides(pattern = guide_legend(override.aes = list(shape = NA)),
           colour = guide_legend(override.aes = list(linetype=0,pattern_colour = "white"))
           )


ggsave2("../Figure_Output/mtDNA_Length_um_aggregated_white.png",p2b, width = 8,height = 6, bg = "transparent")
```



## Calcium Intensity Mito aggregated
```{r}
ag_calcium_mito_3b <- aggregate(res$Intensity_Calcium,res[,c("Diff","Condition","ImageNumber","mtDNA","Compartment")], FUN=mean)
```

#Test for condition effect
```{r}
mod_s3b <- lm(x ~ Condition * mtDNA + Diff, data = ag_calcium_mito_3b[ag_calcium_mito_3b$Compartment == "Processes",])
s3b <- emmeans(mod_s3b, pairwise ~ Condition|mtDNA)
```

```{r}
s3b_df <- as.data.frame(s3b$contrasts)
s3b_df$group1 <- "Ctrl"
s3b_df$group2 <- s3b_df$contrast
s3b_df$group2 <- gsub("Ctrl - ","",s3b_df$group2)
s3b_df <- add_significance(s3b_df,p.col = "p.value")
s3b_df$p.value.num <- round(s3b_df$p.value,3)
s3b_df$p.value.signif[s3b_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- c()
for(i in levels(ag_calcium_mito_3b$mtDNA)) {
  tt <- ag_calcium_mito_3b[ag_calcium_mito_3b$Compartment == "Processes",]
  ll <- max(tt[tt$mtDNA == i ,"x"])
  y_pos <- c(y_pos,ll)
}

s3b_df$y_pos <- y_pos + 0.00025
```

```{r}
p3b <- ggplot(aes(x = Condition, y = x), data = ag_calcium_mito_3b[ag_calcium_mito_3b$Compartment == "Processes",]) +
    geom_violin_pattern(aes(pattern = mtDNA),
                       show.legend = TRUE,
                       linewidth = 0.5, 
                       alpha = 0.7,
                       pattern_color = c("black"),
                       fill = "white",
                       color = "black",
                       pattern_angle = 45,
                       pattern_density = 0.1,
                       pattern_spacing = 0.025,
                       pattern_key_scale_factor = 0.6,) +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      fun.max = function(x) mean(x) + sd(x),
      fun.min = function(x) mean(x) - sd(x),
      geom = "errorbar",
      position = position_dodge(width = 0.5),
      alpha = 0.7,
      size = 0.75,
      width = 0,
      show.legend = FALSE
    ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      geom = "point",
      position = position_dodge(width = 0.5),
      size = 4,   # Point size
      alpha = 0.9,
      show.legend = TRUE
    ) +
    ggsignif::geom_signif(data = s3b_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
    facet_grid(Compartment ~ mtDNA) +
    ylab("Calcium Intensity in Mitochondria") +
    theme_classic(base_size = 18) +
    coord_cartesian(ylim = c(0.003,0.005)) +
    scale_color_manual(values = col_vec) +
    scale_pattern_discrete(choices = c("none","stripe"))+
    theme(strip.text.x = element_text(size = rel(1.1)),
          strip.text.y = element_text(size = rel(1.1)),
          strip.placement = "inside",
          text = element_text(size = 18),
          ) + 
    guides(pattern = guide_legend(override.aes = list(shape = NA)),
           colour = guide_legend(override.aes = list(linetype=0,pattern_colour = "white"))
           )
         

ggsave2("../Figure_Output/mtDNA_Calcium_aggregated_white.png",p3b, width = 8,height = 6, bg = "transparent")
```


#Test for mtDNA effect
```{r}
s3c <- emmeans(mod_s3b, pairwise ~ mtDNA|Condition)
```

```{r}
s3c_df <- as.data.frame(s3c$contrasts)
s3c_df$group1 <- "yes"
s3c_df$group2 <- "no"
s3c_df <- add_significance(s3c_df,p.col = "p.value")
s3c_df$p.value.num <- round(s3c_df$p.value,3)
s3c_df$p.value.signif[s3c_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- c()
for(i in levels(ag_calcium_mito_3b$Condition)) {
  tt <- ag_calcium_mito_3b[ag_calcium_mito_3b$Compartment == "Processes",]
  ll <- max(tt[tt$Condition == i ,"x"])
  y_pos <- c(y_pos,ll)
}

s3c_df$y_pos <- y_pos + 0.00025
```

```{r}
p3c <- ggplot(aes(x = mtDNA, y = x), data = ag_calcium_mito_3b[ag_calcium_mito_3b$Compartment == "Processes",]) +
    geom_violin_pattern(aes(pattern = Condition),
                       show.legend = TRUE,
                       linewidth = 0.5, 
                       alpha = 0.7,
                       pattern_color = c("black"),
                       fill = "white",
                       color = "black",
                       pattern_angle = 45,
                       pattern_density = 0.1,
                       pattern_spacing = 0.025,
                       pattern_key_scale_factor = 0.6,) +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      fun.max = function(x) mean(x) + sd(x),
      fun.min = function(x) mean(x) - sd(x),
      geom = "errorbar",
      position = position_dodge(width = 0.5),
      alpha = 0.7,
      size = 0.75,
      width = 0,
      show.legend = FALSE
    ) +
    stat_summary(aes(color = Diff),
      fun = mean,
      geom = "point",
      position = position_dodge(width = 0.5),
      size = 4,   # Point size
      alpha = 0.9,
      show.legend = TRUE
    ) +
    ggsignif::geom_signif(data = s3c_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
    facet_grid(Compartment ~ Condition) +
    ylab("Calcium Intensity in Mitochondria") +
    theme_classic(base_size = 18) +
    coord_cartesian(ylim = c(0.003,0.005)) +
    scale_color_manual(values = col_vec) +
    scale_pattern_discrete(choices = c("none","stripe"))+
    theme(strip.text.x = element_text(size = rel(1.1)),
          strip.text.y = element_text(size = rel(1.1)),
          strip.placement = "inside",
          text = element_text(size = 18),
          ) + 
    guides(pattern = guide_legend(override.aes = list(shape = NA)),
           colour = guide_legend(override.aes = list(linetype=0,pattern_colour = "white"))
           )
         

ggsave2("../Figure_Output/mtDNA_Calcium_aggregated_white_2.png",p3c, width = 8,height = 6, bg = "transparent")
```




## DNA content
```{r}
ag_perc <- res %>%
  group_by(Diff, Condition, ImageNumber, Compartment) %>%
  summarise(
    total_mito = n(),
    mito_with_mtDNA = sum(mtDNA == "yes"),
    fraction_with_mtDNA = mito_with_mtDNA / total_mito
  ) %>%
  ungroup()
```
```{r}
mod_s4 <- lm(fraction_with_mtDNA ~ Condition + Diff, data = ag_perc[ag_perc$Compartment == "Processes",])
s4 <- emmeans(mod_s4, pairwise ~ Condition)
```

```{r}
s4_df <- as.data.frame(s4$contrasts)
s4_df$group1 <- "Ctrl"
s4_df$group2 <- s4_df$contrast
s4_df$group2 <- gsub("Ctrl - ","",s4_df$group2)
s4_df <- add_significance(s4_df,p.col = "p.value")
s4_df$p.value.num <- round(s4_df$p.value,3)
s4_df$p.value.signif[s4_df$p.value.signif == "ns"] <- NA

#add y_position
tt <- ag_perc[ag_perc$Compartment == "Processes",]
y_pos <- max(tt$fraction_with_mtDNA)
  
s4_df$y_pos <- y_pos + 0.05
```



```{r}
#white
p4 <- ggplot(aes(x = Condition, y = fraction_with_mtDNA), data = ag_perc[ag_perc$Compartment == "Processes",]) +
  geom_violin() +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s4_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
  ylab("% Mitochondria with mtDNA") +
  xlab("") +
  facet_wrap(~Compartment)+
  scale_color_manual(values = col_vec) +
  coord_cartesian(ylim = c(0,0.6)) +
  theme_classic(base_size = 18)+
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        ) + 
  guides(shape = "none")


ggsave2("../Figure_Output/Percentage_mtDNA_aggregated_white.png",p4, width = 5,height = 6, bg = "transparent")
```





## Number Mitos
```{r}
mito_number_per_soma <- res %>%
  group_by(Diff, Condition, ImageNumber) %>%
  filter(max(InSoma) > 0) %>%  # Keep only images with at least 1 soma
  summarise(
    n_total_mito = n(),
    n_mito_outside_soma = sum(InSoma == 0),
    n_mito_inside_soma = sum(InSoma != 0),
    n_soma = max(InSoma),
    mito_processes_per_soma = n_mito_outside_soma / n_soma,
    mito_soma_per_soma = n_mito_inside_soma / n_soma
  ) %>%
  ungroup()
```

```{r}
number_plot <- mito_number_per_soma %>%
  dplyr::select(Diff, Condition, ImageNumber, mito_processes_per_soma, mito_soma_per_soma) %>%
  pivot_longer(
    cols = c(mito_processes_per_soma, mito_soma_per_soma),
    names_to = "Compartment",
    values_to = "number_mitos"
  ) %>%
  mutate(
    Compartment = recode(Compartment,
                         mito_processes_per_soma = "Processes",
                         mito_soma_per_soma = "Soma")
  )

number_plot$Compartment <- factor(number_plot$Compartment, levels = c("Processes","Soma"))
```


```{r}
mod_s5 <- lm(number_mitos ~ Condition*Compartment + Diff, data = number_plot)
s5 <- emmeans(mod_s5, pairwise ~ Condition|Compartment)
```

```{r}
s5_df <- as.data.frame(s5$contrasts)
s5_df$group1 <- "Ctrl"
s5_df$group2 <- s5_df$contrast
s5_df$group2 <- gsub("Ctrl - ","",s5_df$group2)
s5_df <- add_significance(s5_df,p.col = "p.value")
s5_df$p.value.signif <- round(s5_df$p.value,2)

#add y_position
y_pos <- c()
for(i in levels(number_plot$Compartment)) {
  ll <- max(number_plot[number_plot$Compartment == i ,"number_mitos"])
  y_pos <- c(y_pos,ll)
}

  
s5_df$y_pos <- y_pos + 50
s5_df$y_pos2 <- s5_df$y_pos + c(500,100)
```


```{r}
#white
p5 <- ggplot(aes(x = Condition, y = number_mitos), data = number_plot) +
  geom_violin() +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s5_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos2
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
  ylab("# of Mitos per detected Somas") +
  coord_cartesian(ylim = c(0,5500)) +
  xlab("") +
  scale_color_manual(values = col_vec) +
  facet_wrap(~Compartment,nrow = 2, scales = "fixed")+
  theme_classic(base_size = 18)+
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        ) + 
  guides(shape = "none")


ggsave2("../Figure_Output/NumberMitos_white.png",p5, width = 8,height = 10, bg = "transparent")
```







