---
title: "Segmentation_Quantification"
author: "Michael Soutschek"
date: "2024-06-25"
output: html_document
---

#Nv2 Day11 & Day20 are the same

#libraries
```{r}
suppressPackageStartupMessages({
  library(ggplot2)
  library(scales)
  library(ggsci)
  library(cowplot)
  library(ggpattern)
  library(dplyr)
  library(tidyr)
  library(MASS)
  library(emmeans)
  library(ggsignif)
  library(rstatix)
})
```

```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```


#Data Import
```{r}
res_mean <- readRDS("../Data/mean_res.rds")
replacement <- c(Nv11 = "n1", Nv12 = "n2", Nv13 = "n3")
res_mean$Diff <- replacement[as.character(res_mean$Diff)]
res_mean$Diff <- factor(res_mean$Diff,levels = c("n1","n2","n3"))
```


## Percentage of mtDNA

```{r}
mod_s1 <- lm((Count_mtDNAinMito / Count_mtDNA) ~ Condition + Diff, data = res_mean)
s1 <- emmeans(mod_s1, pairwise ~ Condition)
```

```{r}
s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("Ctrl - ","",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")
s1_df$p.value.num <- round(s1_df$p.value,3)
s1_df$p.value.signif[s1_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- max(res_mean$Count_mtDNAinMito / res_mean$Count_mtDNA)

s1_df$y_pos <- y_pos + 0.1
```

```{r}
#white
p1 <- ggplot(aes(x = Condition, y = (Count_mtDNAinMito / Count_mtDNA)), data = res_mean) +
  geom_violin() +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s1_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
  ylab("% mtDNA inside Mitochondria") +
  coord_cartesian(ylim = c(0,1)) +
  scale_color_manual(values = col_vec) +
  xlab("") +
  theme_classic(base_size = 18)+
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        )



ggsave2("../Figure_Output/mtDNA_release_white.png",p1, width = 5,height = 6, bg = "transparent")
```

## Calcium Intensity in Soma

```{r}
res_mean_soma <- res_mean[res_mean$Count_Soma > 0,]
```


```{r}
mod_s2 <- lm(SomaCalciumIntensity ~ Condition + Diff, data = res_mean_soma)
s2 <- emmeans(mod_s2, pairwise ~ Condition)
```

```{r}
s2_df <- as.data.frame(s2$contrasts)
s2_df$group1 <- "Ctrl"
s2_df$group2 <- s2_df$contrast
s2_df$group2 <- gsub("Ctrl - ","",s2_df$group2)
s2_df <- add_significance(s2_df,p.col = "p.value")
s2_df$p.value.num <- round(s2_df$p.value,3)
s2_df$p.value.signif[s2_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- max(res_mean_soma$SomaCalciumIntensity)

s2_df$y_pos <- y_pos + 0.0005
```

```{r}
#white
p2 <- ggplot(aes(x = Condition, y = SomaCalciumIntensity), data = res_mean_soma) +
  geom_violin() +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s2_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
  ggtitle("Soma") +
  ylab("Calcium Intensity in Mitochondria") +
  #coord_cartesian(ylim = c(0,1)) +
  scale_color_manual(values = col_vec) +
  xlab("") +
  theme_classic(base_size = 12)+
 theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  scale_x_discrete(labels=c("pLNA-\nCtrl","pLNA-\n1229"))



ggsave2("../Figure_Output/CalciumIntensity_in_Soma.png",p2, width = 5,height = 4.75, bg = "transparent")
```



## mtDNA intensity
```{r}
mod_s3 <- lm(mtDNAIntensity ~ Condition + Diff, data = res_mean)
s3 <- emmeans(mod_s3, pairwise ~ Condition)
```

```{r}
s3_df <- as.data.frame(s3$contrasts)
s3_df$group1 <- "Ctrl"
s3_df$group2 <- s3_df$contrast
s3_df$group2 <- gsub("Ctrl - ","",s3_df$group2)
s3_df <- add_significance(s3_df,p.col = "p.value")
s3_df$p.value.num <- round(s3_df$p.value,3)
s3_df$p.value.signif[s3_df$p.value.signif == "ns"] <- NA

#add y_position
y_pos <- max(res_mean$mtDNAIntensity)

s3_df$y_pos <- y_pos + 0.0025
```

```{r}
#white
p3 <- ggplot(aes(x = Condition, y = mtDNAIntensity), data = res_mean) +
  geom_violin() +
    stat_summary(
      fun = mean,
      geom="crossbar",
      show.legend = FALSE
      ) +
  stat_summary(aes(color = Diff),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(data = s3_df,
      aes(
      xmin        = group1,
      xmax        = group2,
      annotations = p.value.signif,
      y_position  = y_pos
      ),
      manual      = TRUE,
      textsize    = 4,
      vjust       = -0.1,
      size        = 0.75,
      colour      = "black"
      ) +
  ylab("mtDNA Intensity") +
  #coord_cartesian(ylim = c(0,1)) +
  scale_color_manual(values = col_vec) +
  xlab("") +
  theme_classic(base_size = 18)+
  scale_pattern_discrete(choices = c("none","stripe"))+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.text.y = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 18),
        )



ggsave2("../Figure_Output/mtDNA_Intensity.png",p3, width = 5,height = 6, bg = "transparent")
```
