---
title: "Synpase_Data_Prep"
author: "Michael"
date: "6 12 2020"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(tidyverse)
  library(data.table)
  library(readxl)
  library(stringr)
  library(ggsci)
  library(scales)
  library(cowplot)
  library(readr)
})
```


# Load Data
```{r}
syn_res <- readRDS("../Data/Synapsecluster_Result_TSB_Raw.rds")
```



# cleanup
```{r}
#Length
syn_res$Length <- syn_res$Intensity_TotalIntensity_SkelSomaRm
syn_res$Intensity_TotalIntensity_SkelSomaRm <- NULL
syn_res$Length_um <- syn_res$Length / 14.1607
colnames(syn_res)[which(colnames(syn_res)=="Diff")] <- "Differentiation"
```




# Get unique CSV
```{r}
syn_res$CVSi <- paste(syn_res$Condition,syn_res$CVS,sep = "_")
```


#Filter out images in which no Nucleus is detected
```{r}
syn_res <- syn_res[syn_res$Count_MaskedNuclei != 0,]
```



# Pictures with no detected Synapses don't report an intensity
```{r}
syn_res[is.na(syn_res)] <- 0
```



#Get Synapse Values
```{r}
colnames(syn_res)[which(colnames(syn_res) == "Math_SynByPSDdendArea")] <- "Synapses_by_area"
colnames(syn_res)[which(colnames(syn_res) == "Math_DensitySynByPSDdend")] <- "Synapses_by_length"
colnames(syn_res)[which(colnames(syn_res) == "Math_SynapseDensityPerCell")] <- "Synapses_by_Cell"

colnames(syn_res)[which(colnames(syn_res) == "Count_MaskedSynByPSDdend")] <- "SynapseCounts"
colnames(syn_res)[which(colnames(syn_res) == "AreaOccupied_AreaOccupied_DendMapTubeSomaRm")] <- "DendriteArea"
colnames(syn_res)[which(colnames(syn_res) == "AreaOccupied_AreaOccupied_Soma")] <- "SomaArea"
syn_res$DendriteArea_um2 <- syn_res$DendriteArea / (14.1607^2)


syn_res$Synapses_perArea_um2 <- syn_res$Synapses_by_area * (14.1607^2)
syn_res$Synapses_perLength_um <- syn_res$Synapses_by_length * 14.1607
syn_res$DendArea_per_Nuclei <- syn_res$DendriteArea / syn_res$Count_MaskedNuclei
syn_res$DendArea_um2_per_Nuclei <- syn_res$DendriteArea_um2 / syn_res$Count_MaskedNuclei
syn_res$Length_per_Nuclei <- syn_res$Length / syn_res$Count_MaskedNuclei

syn_res$Synapses_per_DendArea_per_Nuclei <- syn_res$SynapseCounts / syn_res$DendArea_per_Nuclei
syn_res$Synapses_per_DendArea_um2_per_Nuclei <- syn_res$SynapseCounts / syn_res$DendArea_um2_per_Nuclei 
syn_res$Synapses_per_Length_per_Nuclei <- syn_res$SynapseCounts / syn_res$Length_per_Nuclei
```




#Get PSD and Synapsin Densities
```{r}
#PSD per neuron
syn_res$PSD_per_length_micron <- syn_res$Count_PSDMaskByDEND / syn_res$Length_um
syn_res$PSD_per_area <- syn_res$Count_PSDMaskByDEND / syn_res$DendriteArea
syn_res$PSD_per_area_um2 <- syn_res$PSD_per_area * (14.1607^2)
syn_res$PSD_per_area_per_Nuclei <- syn_res$Count_PSDMaskByDEND / syn_res$DendArea_per_Nuclei
syn_res$PSD_per_area_um2_per_Nuclei <- syn_res$Count_PSDMaskByDEND / syn_res$DendArea_um2_per_Nuclei 


#Syn Per neuron
syn_res$Syn_per_length_micron <- syn_res$Count_SynMaskByDend / syn_res$Length_um
syn_res$Syn_per_area <- syn_res$Count_SynMaskByDend / syn_res$DendriteArea
syn_res$Syn_per_area_um2 <- syn_res$Syn_per_area * (14.1607^2)
syn_res$Syn_per_area_per_Nuclei <- syn_res$Count_SynMaskByDend / syn_res$DendArea_per_Nuclei
syn_res$Syn_per_area_um2_per_Nuclei <- syn_res$Count_SynMaskByDend / syn_res$DendArea_um2_per_Nuclei 
```


```{r}
colnames(syn_res)[which(colnames(syn_res) == "Mean_PSDMaskByDEND_Intensity_IntegratedIntensity_PSD95")] <- "Mean_IntegrIntensity_PSD95inDend"
colnames(syn_res)[which(colnames(syn_res) == "Mean_PSDMaskByDEND_Intensity_MeanIntensity_PSD95")] <- "Mean_Intensity_PSD95inDend"

colnames(syn_res)[which(colnames(syn_res) == "Mean_SynMaskByDend_Intensity_IntegratedIntensity_SYN")] <- "Mean_IntegrIntensity_SyninDend"
colnames(syn_res)[which(colnames(syn_res) == "Mean_SynMaskByDend_Intensity_MeanIntensity_SYN")] <- "Mean_Intensity_SyninDend"
```

```{r}
syn_res <- syn_res[,-grep("StDev_",colnames(syn_res))]
```



#cleanup
```{r}
syn_res$Condition <- factor(syn_res$Condition, levels = c("empty","pLNA-Ctrl","pLNA-1229","TSB"))
syn_res$Differentiation <- factor(syn_res$Differentiation)
```


# save
```{r}
saveRDS(syn_res,"../Data/Synapsecluster_Result_TSB.rds")
```





# exploratory
```{r}
options(digits=4)

p1 <- ggplot(syn_res,aes(x = Condition, y = sqrt(Synapses_per_DendArea_um2_per_Nuclei))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = Differentiation)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~Differentiation) +
  theme_classic()

p2 <- ggplot(syn_res,aes(x = Condition, y = sqrt(PSD_per_area_um2_per_Nuclei))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  theme_classic()

p3 <- ggplot(syn_res,aes(x = Condition, y = sqrt(Syn_per_area_um2_per_Nuclei))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  theme_classic()

p4a <- ggplot(syn_res,aes(x = Differentiation, y = DendArea_um2_per_Nuclei)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  coord_cartesian(ylim = c(0,NA)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  theme_classic() 

p4b <- ggplot(syn_res,aes(x = Condition, y = DendArea_um2_per_Nuclei)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  coord_cartesian(ylim = c(0,NA)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~Differentiation,nrow = 1) +
  theme_classic() 

p4c <- ggplot(syn_res,aes(x = Condition, y = DendArea_um2_per_Nuclei)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = median,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  coord_cartesian(ylim = c(0,NA)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  facet_wrap(~Differentiation,nrow = 1) +
  theme_classic() 

p5 <- ggplot(syn_res,aes(x = Diff, y = Synapses_per_DendArea_um2_per_Nuclei)) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point(aes(color = CVS)) +
  ylim(0,NA) +
  scale_y_continuous(labels = comma) +
  theme_classic()
```


