---
title: "miRNAexpression_Denmark"
author: "Michael Soutschek"
date: "2025-07-25"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(tidyr)
  library(ggplot2)
  library(emmeans)
  library(readxl)
  library(scales)
  library(ggsci)
  library(ggplot2)
  library(MASS)
  library(emmeans)
  library(cowplot)
  library(rstatix)
  library(ggpattern)
  library(dplyr)
  library(patchwork)
})
```

########
## HIP
```{r}
hip <- read_excel("../HIP_Beregnet med Ctunder 30.xlsx", 
    skip = 2)
hip$...8 <- NULL
hip <- hip[hip$Diagnosis != "psychosis manio-depressiva",]
```

```{r}
hip[ , 3:8] <- lapply(hip[ , 3:8], as.character)
```


```{r}
hip_long <- pivot_longer(
  data = hip,
  cols = `125b-5p`:`1229-3p`,
  names_to = "miRNA",
  values_to = "value"
)
```

```{r}
hip_long$value[hip_long$value == "No Cq"] <- NA
hip_long$value <- as.numeric(hip_long$value)
hip_long$miRNA <- factor(hip_long$miRNA)
hip_long$Diagnosis <- gsub("depression","Depression",hip_long$Diagnosis)
hip_long$Diagnosis <- gsub("schizoprenia","Schizoprenia ",hip_long$Diagnosis)
```

```{r}
#Filter above 30
hip_long$value[hip_long$value > 30] <- NA
```

```{r}
saveRDS(hip_long,"./HIP.rds")
```

```{r}
hip_long <- readRDS("./HIP.rds")
```


```{r}
p1 <- ggplot(hip_long,aes(x = miRNA, y = value)) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point() +
  #coord_cartesian(ylim = c(0,NA)) +
  ylab("Cq-Value") +
  facet_wrap(Sex~Diagnosis) +
  theme_classic(base_size = 12)+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  ggtitle("Hippocampus") 

p1 <- p1 + plot_annotation(
  caption = "\nEfficiencies: 1229-3p - 112% / 125b-5p - 102% / 128-3p - 106% / 146a-5p - 102% / 210-3p - 101%  / 485-5p - 91",
  theme = theme(plot.caption = element_text(hjust = 1, size = 12,colour = "grey36",face = "italic"))
)

ggsave("../FigureOutput/HIP.png",p1, width = 14,height = 10, bg = "white")
```




########
## PFC
```{r}
pfc <- read_excel("../PFC_Beregnet med Ctunder 30.xlsx", 
    skip = 1)
pfc$...3 <- NULL
```





```{r}
pfc[ , 3:8] <- lapply(pfc[ , 3:8], as.character)
colnames(pfc)[which(colnames(pfc)=="miR-1229-3p")] <- "1229-3p"
```


```{r}
pfc_long <- pivot_longer(
  data = pfc,
  cols = `1229-3p`:`210-3p`,
  names_to = "miRNA",
  values_to = "value"
)
```

```{r}
pfc_long$value[pfc_long$value == "No Cq"] <- NA
pfc_long$value <- as.numeric(pfc_long$value)
pfc_long$miRNA <- factor(pfc_long$miRNA)
pfc_long$Diagnosis <- gsub("depression","Depression",pfc_long$Diagnosis)
pfc_long$Diagnosis <- gsub("schizoprenia","Schizoprenia ",pfc_long$Diagnosis)
```

```{r}
#Filter above 30
pfc_long$value[pfc_long$value > 30] <- NA
```

```{r}
saveRDS(pfc_long,"./PFC.rds")
```

```{r}
pfc_long <- readRDS("./PFC.rds")
```


```{r}
p2 <- ggplot(pfc_long,aes(x = miRNA, y = value)) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  geom_point() +
  #coord_cartesian(ylim = c(0,NA)) +
  ylab("Cq-Value") +
  facet_wrap(Sex~Diagnosis) +
  theme_classic(base_size = 12)+
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1))) +
  ggtitle("Prefrontal Cortex") 

p2 <- p2 + plot_annotation(
  caption = "\nEfficiencies: 1229-3p - / 125b-5p - 105 / 126-3p - 103 / 128-3p - 103 / 146a-5p - 105 / 191-5p - 103 / 210-3p - 107",
  theme = theme(plot.caption = element_text(hjust = 1, size = 12,colour = "grey36",face = "italic"))
)

ggsave("../FigureOutput/PFC.png",p2, width = 14,height = 10, bg = "white")
```

















