---
title: "longRNA-exploratory"
author: "Michael Soutschek"
date: "11 1 2021"
output: html_document
---

```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(plotly)
  library(cowplot)
})
```


# Load Data
```{r}
se <- readRDS("../../data/Long_RNA/longRNA.DEA.SE.rds")
se$Day <- paste0("Day ",se$day)
se$Day[which(se$Day == "Day 9")] <- "Day 09"
se$Day <- factor(se$Day, levels = c("Day 0","Day 09","Day 15","Day 21","Day 27","Day 33","Day 40"))
se$day <- as.factor(se$day)
se$day2 <- paste0("Day_",se$day)
se$replicate <- as.integer(gsub("SC","",se$experiment))
se2 <- se[,se$day != 0]
```



# Violine Figures:
```{r}
# example to get genes:
#g <- grep("\\.SOX2$|\\.POU5F1$|LIN28A", row.names(se), value=TRUE)
#g
# or:
g1 <- row.names(se)[ rowData(se)$symbol %in% c("SOX2","POU5F1","LIN28A")]
g1

g2 <- row.names(se)[ rowData(se)$symbol %in% c("SYN1","GRIA2","GRIA4","GRIN2B","GRIN2A")]
g2

# g3 <- row.names(se)[ rowData(se)$symbol %in% c("SLC1A3","SOX10","SOX9","GFAP","ALDH1L1","S100B","AQP4","MOG","OLIG2")]
# g3

g4 <- row.names(se)[ rowData(se)$symbol %in% c("MGAT4B")]
g4

png("Figure_Output/Single_Genes/Paper/Pluripotency_marker.png", width=8, height=4, units="in", res=300)
ggplot(meltSE(se, g1, assayName = "logcpm"), aes(as.factor(day), logcpm)) + geom_violin() + facet_wrap(~feature, scale="free") + geom_point(aes(color = experiment)) + xlab("Day") + theme_classic()
dev.off()


png("Figure_Output/Single_Genes/Paper/longRNA_syn-genes-examp.png", width=11, height=3, units="in", res=300)
ggplot(meltSE(se, g2, assayName = "logcpm"), aes(as.factor(day), logcpm)) + geom_violin() + facet_wrap(~feature, scale="free", nrow = 1) +
geom_point(aes(color = experiment)) + xlab("Day") + theme_classic()
dev.off()


se2 <- se
row.names(se2) <- sapply(strsplit(row.names(se),"\\."),"[",2)
g3 <- row.names(se2)[ rowData(se2)$symbol %in% c("SLC1A3","SOX10","SOX9","GFAP","ALDH1L1","S100B","AQP4","MOG","OLIG2")]
g3


png("Figure_Output/Single_Genes/Paper/longRNA_glia-marker.png", width=6, height=6, units="in", res=300)
ggplot(meltSE(se2, g3, assayName = "logcpm"), aes(as.factor(day), logcpm)) + geom_violin() + facet_wrap(~feature, scale="free") +
geom_point(aes(color = experiment)) + xlab("Day") + theme_classic()
dev.off()

png("Figure_Output/Single_Genes/Paper/Mgat4b.png", width=4, height=3, units="in", res=300)
ggplot(meltSE(se, g4, assayName = "logcpm"), aes(as.factor(day), logcpm)) + geom_violin() + facet_wrap(~feature, scale="free") +
geom_point(aes(color = experiment)) + xlab("Day") + theme_classic() + coord_cartesian(ylim = c(0,NA))
dev.off()

```






## PCA

```{r pca, message=FALSE, warning=FALSE, eval=TRUE}

## all stages
p <- plPCA(assays(se)$logcpm, as.data.frame(colData(se)), colorBy = "Day", shapeBy = "replicate",add.labels = FALSE)

orca(p, file = "Figure_Output/Exploratory/LongRNA_PCA.png")
orca(p, file = "Figure_Output/Exploratory/LongRNA_PCA.pdf")
```






```{r}
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[2],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
col_vec2 <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])


#assay
x <- assays(se)$logcpm

#preparation
x <- t(x[which(!(apply(x, 1, var) == 0)), ])
pca <- prcomp(x)

#annotation
samples_data = as.data.frame(colData(se))
annotation_columns = colnames(colData(se))

samples_data <- samples_data[row.names(pca$x), ]
samples_data$names <- row.names(samples_data)
labs <- annotation_columns
labs[which(labs == "names")] <- ""
text <- apply(samples_data[, annotation_columns, drop = F], 
                  1, labs = labs, FUN = function(x, labs) {
                    paste(paste(labs, x), collapse = "\n")
                  })

#annotation
colorBy = "Day"
shapeBy = "replicate"

cb <- samples_data[, colorBy]
if (is.numeric(cb)) cb <- as.character(cb)

sb <- samples_data[, shapeBy]
if (is.numeric(sb)) sb <- as.factor(as.character(sb))


#plot components
xlab <- paste("PC ", "1", " (", round(pca$sdev[1]/sum(pca$sdev) *
                                                       100, 0), "%)", sep = "")
ylab <- paste("PC ", "2", " (", round(pca$sdev[2]/sum(pca$sdev) *
                                                       100, 0), "%)", sep = "")

df <- data.frame(x = pca$x[,1],y = pca$x[,2])

p1 <- ggplot(df, aes(x = x, y = y)) +
  geom_hline(yintercept=0, linewidth = 0.25) +
  geom_vline(xintercept=0, linewidth = 0.25) +
  geom_point(aes(color = cb, shape = sb),size = 3) +
  theme_classic() +
  xlab(xlab) + ylab(ylab) + 
  #scale_color_manual(values = col_vec2) +
  scale_color_uchicago()+
  theme(text = element_text(size = 14), 
        axis.text.x = element_text(size = rel(1)),
        axis.text.y = element_text(size = rel(1))) +
  guides(color=guide_legend(title="Day"),shape=guide_legend(title="Differentiation"))
  

  ggsave("./Figure_Output/Exploratory/PCA_man.png",p1, width = 6.5,height = 4.5, bg = "white")

```
















