---
title: "longRNA_Heat_Figures"
author: "Michael Soutschek"
date: "11 1 2021"
output: html_document
---



```{r}
suppressPackageStartupMessages({
  library(SummarizedExperiment)
  library(SEtools)
  library(ggplot2)
  library(plgINS)
  library(viridis)
  library(RColorBrewer)
  library(data.table)
  library(dplyr)
  library(tidyr)
  library(sechm)
})
```


# Color Definitions
```{r}
ancols <- list(day=c("0"="#3F3F3F",
                       "9" ="#575757",
                       "15" ="#707070",
                       "21" = "#898989",
                       "27" ="#A1A1A1",
                       "33" ="#BABABA",
                       "40" = "#D3D3D3" 
) )

heatcol = inferno(255)
```




# Load Data
```{r}
se <- readRDS("../../RNA_GRCh38.p10_Ens91/data/Long_RNA/longRNA.DEA.SE.rds")
se$day <- as.factor(se$day)
se2 <- se[,se$day != 0]
```



## Figures

```{r significant results, eval=TRUE}
# select significant results
## all stages
res <- rowData(se)$DEA.all
res$maxlfc <- rowMax(abs(as.matrix(res[,1:6]))) 
sig_all <- row.names(res)[res$FDR < 0.05]
sig_all_01 <- row.names(res)[res$FDR < 0.01]
sig <- row.names(res)[res$FDR < 0.01 & res$maxlfc > 2]
sig_plot <- row.names(res)[res$FDR < 0.01 & res$maxlfc > 2 & res$logCPM > 3]

## neuronal stages
res.neu <- rowData(se)$DEA.neuronal
res.neu$maxlfc <- rowMax(abs(as.matrix(res.neu[,1:5]))) 
sig.neu <- row.names(res.neu)[res.neu$FDR < 0.01 & res.neu$maxlfc > 2]
```




# Heatmaps
```{r}
# # all days
# sechm(se, sig_plot, anno_columns=c("day"), assayName = "log2FC.all", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# 
# png("Figure_Output/Heat/LongRNA_Heat_alldays.png", width=7, height=5, units="in", res=300)
# sehm(se, sig_plot, anno_columns=c("day"), assayName = "log2FC.all", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# dev.off()
# 
# 
# 
# # all days, normalized Day9
# sehm(se, sig_plot, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# 
# png("Figure_Output/Heat/Heat_alldays_normDay9.png", width=7, height=5, units="in", res=300)
# sehm(se, sig_plot, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# dev.off()
# 
# 
# 
# # neuronal days
# sehm(se2, sig.neu, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# 
# png("Figure_Output/Heat/Heat_neudays.png", width=7, height=5, units="in", res=300)
# sehm(se2, sig.neu, anno_columns=c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols,annotation_names_col = FALSE)
# dev.off()
```



# lncRNAs
```{r}
lncRNA.se <- se[rowData(se)$biotype == "lincRNA"]
# Number of significant lncRNAs
sum(sig_all_01 %in% row.names(lncRNA.se))
sum(sig_all %in% row.names(lncRNA.se))


# lncRNAs all days, normalized Day9
a <- sechm(lncRNA.se, sig_all_01, top_annotation =c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols, show_colnames = FALSE, column_title = "lncRNA", name = "logFC", annocol_title_side=NA)

png("Figure_Output/Heat/LongRNA_lncRNA_alldays_normDay9.png", width=7, height=5, units="in", res=300)
a
dev.off()
png("Figure_Output/Heat/LongRNA_lncRNA_alldays_normDay9_defense.png", width=6, height=4.5, units="in", res=300)
a
dev.off()



# Top 15 candidates lncRNAs neuronal
res.neu.lncRNA <- res.neu[row.names(res.neu) %in% row.names(lncRNA.se),]
top10.neu.lncRNA <- row.names(head(res.neu.lncRNA[order(res.neu.lncRNA$FDR),],10))
top10.neu.lncRNA <- sapply(strsplit(top10.neu.lncRNA,"\\."),"[",2)
row.names(lncRNA.se) <- sapply(strsplit(row.names(lncRNA.se),"\\."),"[",2)


a <- sechm(lncRNA.se, top10.neu.lncRNA,  top_annotation =c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols, show_colnames = FALSE, column_title = "lncRNA Top 10 sig.", name = "logFC", annocol_title_side=NA)


png("Figure_Output/Heat/LongRNA_lncRNA_alldays_normDay9_Top10_neur.png", width=5.5, height=5, units="in", res=300)
a
dev.off()
```




# mRNAs
```{r}
mRNA.se <- se[rowData(se)$biotype == "protein_coding"]
# Number of significant lncRNAs
sum(sig_all_01 %in% row.names(mRNA.se))
sum(sig_all %in% row.names(mRNA.se))
sum(sig_plot %in% row.names(mRNA.se))

# all days, normalized Day9
a <- sechm(mRNA.se, sig_plot, top_annotation =c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = FALSE, hmcols = heatcol, anno_colors = ancols, show_colnames = FALSE, column_title = "mRNA", name = "logFC", annocol_title_side=NA)


png("Figure_Output/Heat/Heat_mRNAs_alldays_normDay9.png", width=8, height=6, units="in", res=300)
a
dev.off()
```



# mito Genes
```{r}
se_mito <- se
row.names(se_mito) <- sapply(strsplit(row.names(se_mito),"\\."),"[",2)
MT_genes <- grep(pattern = "^MT-C|^MT-A|^MT-N",row.names(se_mito))


heatcol <- c("#4B0C6B","#CF4446","#FFAD33")

# all days, normalized Day9
c <- sechm(se_mito, MT_genes, top_annotation =c("day"), assayName = "log2FC.neur", gaps_at = "day", breaks=TRUE, show_rownames = TRUE, hmcols = heatcol, anno_colors = ancols, show_colnames = FALSE, column_title = "Mitochondrial mRNAs", do.scale = FALSE, name = "logFC", annocol_title_side=NA)


png("Figure_Output/Heat/Heat_mitoGenes_alldays_normDay9.png", width=8, height=4, units="in", res=300)
c
dev.off()
```







