---
title: "GO_Figure"
author: "Michael"
date: "4 3 2020"
output: html_document
---

```{r}
library(RColorBrewer)
library(ggplot2)
library(plyr)
library(data.table)
```



#Import
```{r}
CC <- readRDS("./GO_CB_CC_Comp_elim.rds")
MF <- readRDS("./GO_CB_MF_Comp_elim.rds")
BP <- readRDS("./GO_CB_BP_Comp_elim.rds")
```


#Data preparaion
Filter
CC < 1000
BP < 300
MF <- no filter
```{r}
CC_Top <- CC[which(CC$Annotated < 1000),]
BP_Top <- BP[which(BP$Annotated < 300),]
MF_Top <- MF
```



```{r}
CC_Top <- CC_Top[1:10,]
BP_Top <- BP_Top[1:10,]
MF_Top <- MF_Top[1:10,]

#Create uniform label fields
CC_Top$label1 <- 1.1e-05
CC_Top$label2 <- 1.11

MF_Top$label1 <- 1.1e-05
MF_Top$label2 <- 1.11

BP_Top$label1 <- 1.1e-05
BP_Top$label2 <- 1.11
```


```{r}
CC_Top$Fisher.elim <- as.numeric(CC_Top$Fisher.elim)
CC_Top$rank <- frank(CC_Top$Fisher.elim, ties.method = "first")

MF_Top$Fisher.elim <- as.numeric(MF_Top$Fisher.elim)
MF_Top$rank <- frank(MF_Top$Fisher.elim, ties.method = "first")

BP_Top$Fisher.elim <- as.numeric(BP_Top$Fisher.elim)
BP_Top$rank <- frank(BP_Top$Fisher.elim, ties.method = "first")
```






```{r}

factor_CC <- factor(CC_Top$rank, levels = CC_Top$rank, labels = CC_Top$GO.ID)

factor_MF <- factor(MF_Top$rank, levels = MF_Top$rank, labels = MF_Top$GO.ID)

factor_BP <- factor(BP_Top$rank, levels = BP_Top$rank, labels = BP_Top$GO.ID)

```




## Figures

Define Plot components
```{r}
txt <- element_text(family = "sans", size = 14, colour = "black")
tick <- element_line(size = 1)
```




Figrue CC
```{r}
p <- ggplot(data = CC_Top, aes(x = as.factor(CC_Top$GO.ID))) +
  scale_x_discrete(labels = rev(CC_Top$Term), limits = rev(levels(factor_CC)), name = "")+
  geom_bar(aes(y = CC_Top$Significant), fill = "#E18727", stat = "identity") +
  geom_label(aes(label = CC_Top$label1, y = 0),colour = NA, fill = "#636363") +
  geom_text(aes(label = CC_Top$Fisher.elim, y = 0), colour = "white") +
  geom_label(label = CC_Top$label2, y = 170,label.size = 5, colour = NA, fill = "#636363") +
  geom_text(aes(label = round(CC_Top$Fold_Enrichment,2), y = 170), colour = "white") +
  scale_y_continuous(limits = c(0,175), name = "Number of Genes")+ 
  coord_flip(clip = "off", xlim = c(1,10)) +
  annotate("label", x = 10.9, y = 0,colour = NA,label = "P.Value", fill = "#636363") +
  annotate("text", x = 10.9, y = 0,label= "P.Value",colour = "white") +
  annotate("label", x = 10.9, y = 170,colour = NA,label = "Enrichment", fill = "#636363") +
  annotate("text", x = 10.9, y = 170,label= "Enrichment",colour = "white") +
  theme(axis.title = txt, axis.text = txt,  axis.ticks = tick, plot.margin = unit(c(3,1,1,1),"lines"))

p

ggsave("CB_CC_Comp.png", width=12, height=5, units="in", dpi=300)
ggsave("CB_CC_Comp.pdf", width=12, height=5, units="in", dpi=300)
```

Figrue MF
```{r}
p <- ggplot(data = MF_Top, aes(x = as.factor(MF_Top$GO.ID))) +
  scale_x_discrete(labels = rev(MF_Top$Term), limits = rev(levels(factor_MF)), name = "")+
  geom_bar(aes(y = MF_Top$Significant), fill = "#E18727", stat = "identity") +
  geom_label(aes(label = MF_Top$label1, y = 0),colour = NA, fill = "#636363") +
  geom_text(aes(label = MF_Top$Fisher.elim, y = 0), colour = "white") +
  geom_label(label = MF_Top$label2, y = 50,label.size = 5, colour = NA, fill = "#636363") +
  geom_text(aes(label = round(MF_Top$Fold_Enrichment,2), y = 50), colour = "white") +
  scale_y_continuous(limits = c(0,50), name = "Number of Genes")+ 
  coord_flip(clip = "off", xlim = c(1,10)) +
  annotate("label", x = 10.9, y = 0,colour = NA,label = "P.Value", fill = "#636363") +
  annotate("text", x = 10.9, y = 0,label= "P.Value",colour = "white") +
  annotate("label", x = 10.9, y = 50,colour = NA,label = "Enrichment", fill = "#636363") +
  annotate("text", x = 10.9, y = 50,label= "Enrichment",colour = "white") +
  theme(axis.title = txt, axis.text = txt,  axis.ticks = tick, plot.margin = unit(c(3,1,1,1),"lines"))

p
  
  
ggsave("CB_MF_Comp.png", width=12, height=5, units="in", dpi=300)
ggsave("CB_MF_Comp.pdf", width=12, height=5, units="in", dpi=300)
```


Figrue BP
```{r}
p <- ggplot(data = BP_Top, aes(x = as.factor(BP_Top$GO.ID))) +
  scale_x_discrete(labels = rev(BP_Top$Term), limits = rev(levels(factor_BP)), name = "")+
  geom_bar(aes(y = BP_Top$Significant), fill = "#E18727", stat = "identity") +
  geom_label(aes(label = BP_Top$label1, y = 0),colour = NA, fill = "#636363") +
  geom_text(aes(label = BP_Top$Fisher.elim, y = 0), colour = "white") +
  geom_label(label = BP_Top$label2, y = 50,label.size = 5, colour = NA, fill = "#636363") +
  geom_text(aes(label = round(BP_Top$Fold_Enrichment,2), y = 50), colour = "white") +
  scale_y_continuous(limits = c(0,50), name = "Number of Genes")+ 
  coord_flip(clip = "off", xlim = c(1,10)) +
  annotate("label", x = 10.9, y = 0,colour = NA,label = "P.Value", fill = "#636363") +
  annotate("text", x = 10.9, y = 0,label= "P.Value",colour = "white") +
  annotate("label", x = 10.9, y = 50,colour = NA,label = "Enrichment", fill = "#636363") +
  annotate("text", x = 10.9, y = 50,label= "Enrichment",colour = "white") +
  theme(axis.title = txt, axis.text = txt,  axis.ticks = tick, plot.margin = unit(c(3,1,1,1),"lines"))
p

ggsave("CB_BP_Compk.png", width=12, height=5, units="in", dpi=300)
ggsave("CB_BP_Compk.pdf", width=12, height=5, units="in", dpi=300)
```



```{r}
rm(CC,CC_Top,MF,MF_Top,BP,BP_Top,factor_BP,factor_CC,factor_MF,p)
```


