---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
})
```




#Load Data
```{r}
e <- readRDS("../DataPrep/IndMito.rds")
```


```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```



##################
##################
## Processes Mitos

## Filter out those which are not directly attributable to Axon or Dend
```{r}
#mitos
Mito_processes <- e[e$Mito_Parent_Axons != 0 | e$Mito_Parent_DendSomaRm != 0,]
Mito_processes <- Mito_processes[!(Mito_processes$Mito_Parent_Axons > 0 & Mito_processes$Mito_Parent_DendSomaRm > 0),]
```


```{r}
#area
ag_area <- aggregate(log(Mito_processes$Mito_AreaShape_Area),Mito_processes[,c("Differentiation","Condition")], FUN=mean)

mod_s1 <- rlm(x ~ Condition + Differentiation ,data = ag_area)
s1 <- emmeans(mod_s1, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "pLNA-Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s1_df$group2)
s1_df$group2 <- gsub("\\(", "",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")

#add y_position
y_pos <-max(log(Mito_processes[,"Mito_AreaShape_Area"]))
s1_df$y_pos <- y_pos*1.05



p1 <- ggplot(Mito_processes,aes(x = Condition, y = log(Mito_AreaShape_Area))) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.35), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("MitoArea Processes\nper Image (log)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  #coord_cartesian(ylim = c(0,7)) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/MitoArea_Processes.png",p1, width = 6,height = 4.5, bg = "white")
```


```{r}
#length
ag_length <- aggregate(log(Mito_processes$Skeleton_Length),Mito_processes[,c("Differentiation","Condition")], FUN=mean)
mod_s2 <- rlm(x ~ Condition + Differentiation,data = ag_length)
s2 <- emmeans(mod_s2, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s2_df <- as.data.frame(s2$contrasts)
s2_df$group1 <- "pLNA-Ctrl"
s2_df$group2 <- s2_df$contrast
s2_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s2_df$group2)
s2_df$group2 <- gsub("\\(", "",s2_df$group2)
s2_df <- add_significance(s2_df,p.col = "p.value")

#add y_position
y_pos <-max(log(Mito_processes[,"Skeleton_Length"]))
s2_df$y_pos <- y_pos*1.05

p2 <- ggplot(Mito_processes,aes(x = Condition, y = log(Skeleton_Length))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s2_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("MitoLength Processes\nper Image (log)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  #coord_cartesian(ylim = c(0,7)) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/MitoLength_Processes.png",p2, width = 6,height = 4.5, bg = "white")
```


```{r}
#Intensity
ag_inten <- aggregate(log(Mito_processes$Mito_MeanIntensity),Mito_processes[,c("Differentiation","Condition")], FUN=mean)
mod_s3 <- rlm(x ~ Condition + Differentiation,data = ag_inten)
s3 <- emmeans(mod_s3, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s3_df <- as.data.frame(s3$contrasts)
s3_df$group1 <- "pLNA-Ctrl"
s3_df$group2 <- s3_df$contrast
s3_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s3_df$group2)
s3_df$group2 <- gsub("\\(", "",s3_df$group2)
s3_df <- add_significance(s3_df,p.col = "p.value")
s3_df$p.value.signif <- round(s3_df$p.value,3)

#add y_position
y_pos <- max(log(Mito_processes[,"Mito_MeanIntensity"]))
s3_df$y_pos <- y_pos + 0.1

p3 <- ggplot(Mito_processes,aes(x = Condition, y = log(Mito_MeanIntensity))) +
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s3_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("Mito MeanIntensity Processes\nper Image (log)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  #coord_cartesian(ylim = c(0,7)) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/MitoMeanIntensity_Processes.png",p3, width = 6,height = 4.5, bg = "white")
```






##################
##################
## Dend

```{r}
Mito_Dend <- Mito_processes[Mito_processes$Mito_Parent_Axons == 0,]
```



```{r}
#area
# ag_area_dend <- aggregate(log(Mito_Dend$Mito_AreaShape_Area),Mito_Dend[,c("Differentiation","Condition")], FUN=mean)
# 
# mod_s5 <- rlm(x ~ Condition + Differentiation,data = ag_area_dend)
# emmeans(mod_s5, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")
# 
# p5 <- ggplot(Mito_Dend,aes(x = Condition, y = log(Mito_AreaShape_Area))) +
#   geom_violin(show.legend = FALSE) +
#   stat_summary(
#     fun = mean,
#     geom="crossbar",
#     show.legend = FALSE
#   ) +
#   stat_summary(aes(color = Differentiation),
#     show.legend = TRUE,
#     fun = mean,
#     fun.max = function(x) {mean(x) + sd(x)},
#     fun.min = function(x) {mean(x) - sd(x)},
#     geom="pointrange", position=position_dodge(width=0.5), size = 0.75
#   ) +
#   geom_point(aes(color = Differentiation),alpha = 0.4,position=position_dodge(width=0.35)) +
#   ylab("MitoArea per Image - Dendrites (log)") +
#   theme_classic(base_size = 12)+
#   scale_color_manual(values = col_vec) +
#   #coord_cartesian(ylim = c(0,7)) +
#   theme(strip.text.x = element_text(size = rel(1.1)),
#         strip.placement = "inside",
#         text = element_text(size = 14),
#         axis.title.x=element_blank(),
#         axis.text.x = element_text(size = rel(1)))
# 
#   ggsave2("../Figures/Processes/MitoArea_Dend.png",p5, width = 6,height = 4.5, bg = "white")
```


```{r}
# #length
# ag_length_dend <- aggregate(log(Mito_Dend$Skeleton_Length),Mito_Dend[,c("Differentiation","Condition")], FUN=mean)
# mod_s6 <- rlm(x ~ Condition + Differentiation,data = ag_length_dend)
# emmeans(mod_s6, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")
# 
# p6 <- ggplot(Mito_Dend,aes(x = Condition, y = log(Skeleton_Length))) +
#   geom_violin(show.legend = FALSE) +
#   stat_summary(
#     fun = mean,
#     geom="crossbar",
#     show.legend = FALSE
#   ) +
#   stat_summary(aes(color = Differentiation),
#     show.legend = TRUE,
#     fun = mean,
#     fun.max = function(x) {mean(x) + sd(x)},
#     fun.min = function(x) {mean(x) - sd(x)},
#     geom="pointrange", position=position_dodge(width=0.5), size = 0.75
#   ) +
#   ylab("MitoLength per Image - Dendrites (log)") +
#   theme_classic(base_size = 12)+
#   scale_color_manual(values = col_vec) +
#   #coord_cartesian(ylim = c(0,7)) +
#   theme(strip.text.x = element_text(size = rel(1.1)),
#         strip.placement = "inside",
#         text = element_text(size = 14),
#         axis.title.x=element_blank(),
#         axis.text.x = element_text(size = rel(1)))
# 
# ggsave2("../Figures/Processes/MitoLength_Dend.png",p6, width = 6,height = 4.5, bg = "white")
```






##################
##################
## Axon

```{r}
Mito_Axon <- Mito_processes[Mito_processes$Mito_Parent_DendSomaRm == 0,]
```



```{r}
# #area
# ag_area_axon <- aggregate(log(Mito_Axon$Mito_AreaShape_Area),Mito_Axon[,c("Differentiation","Condition")], FUN=mean)
# mod_s9 <- rlm(x ~ Condition + Differentiation,data = ag_area_axon)
# emmeans(mod_s9, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")
# 
# p9 <- ggplot(Mito_Axon,aes(x = Condition, y = log(Mito_AreaShape_Area))) +
#   geom_violin(show.legend = FALSE) +
#   stat_summary(
#     fun = mean,
#     geom="crossbar",
#     show.legend = FALSE
#   ) +
#   stat_summary(aes(color = Differentiation),
#     show.legend = TRUE,
#     fun = mean,
#     fun.max = function(x) {mean(x) + sd(x)},
#     fun.min = function(x) {mean(x) - sd(x)},
#     geom="pointrange", position=position_dodge(width=0.5), size = 0.75
#   ) +
#   ylab("MitoArea per Image - Axons (log)") +
#   theme_classic(base_size = 12)+
#   scale_color_manual(values = col_vec) +
#   #coord_cartesian(ylim = c(0,7)) +
#   theme(strip.text.x = element_text(size = rel(1.1)),
#         strip.placement = "inside",
#         text = element_text(size = 14),
#         axis.title.x=element_blank(),
#         axis.text.x = element_text(size = rel(1)))
# 
# ggsave2("../Figures/Processes/MitoArea_Axon.png",p9, width = 6,height = 4.5, bg = "white")
```


```{r}
# #length
# ag_length_axon <- aggregate(log(Mito_Axon$Skeleton_Length),Mito_Axon[,c("Differentiation","Condition")], FUN=mean)
# 
# mod_s10 <- rlm(x ~ Condition + Differentiation, data = ag_length_axon)
# emmeans(mod_s10, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")
# 
# p10 <- ggplot(ag_length_axon,aes(x = Condition, y = x)) +
#   geom_violin(show.legend = FALSE) +
#   stat_summary(
#     fun = mean,
#     geom="crossbar",
#     show.legend = FALSE
#   ) +
#   stat_summary(aes(color = Differentiation),
#     show.legend = TRUE,
#     fun = mean,
#     fun.max = function(x) {mean(x) + sd(x)},
#     fun.min = function(x) {mean(x) - sd(x)},
#     geom="pointrange", position=position_dodge(width=0.5), size = 0.75
#   ) +
#   ylab("MitoLength per Image - Axons (log)") +
#   theme_classic(base_size = 12)+
#   scale_color_manual(values = col_vec) +
#   #coord_cartesian(ylim = c(0,7)) +
#   theme(strip.text.x = element_text(size = rel(1.1)),
#         strip.placement = "inside",
#         text = element_text(size = 14),
#         axis.title.x=element_blank(),
#         axis.text.x = element_text(size = rel(1)))
# 
# ggsave2("../Figures/MitoLength_Axon.png",p10, width = 6,height = 4.5, bg = "white")
```




##################
##################
## Number of Mitos in Dendrites and Axons

```{r}
ImageMeans <- readRDS("../DataPrep/SomaMito.rds")
```


#Dendrites
```{r}
ag_number_dend <- aggregate(Mito_Dend$Name_FileName,Mito_Dend[,c("Differentiation","Condition","CVS","Image")], FUN=length)
ag_number_dend <- merge(ag_number_dend,ImageMeans[,c("Differentiation","Condition","CVS","Image","Area_DendSomaRm")],by = c("Differentiation","Condition","CVS","Image"), all.x = TRUE)

ag_number_dend$Mito_per_Area_Dend <- ag_number_dend$x / ag_number_dend$Area_DendSomaRm
```



```{r}
ag_number_dend_stat <- aggregate(sqrt(ag_number_dend$Mito_per_Area_Dend),ag_number_dend[,c("Differentiation","Condition")], FUN=mean)
mod_s13 <- rlm(x ~ Condition + Differentiation,data = ag_number_dend_stat)
s13 <- emmeans(mod_s13, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")


s13_df <- as.data.frame(s13$contrasts)
s13_df$group1 <- "pLNA-Ctrl"
s13_df$group2 <- s13_df$contrast
s13_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s13_df$group2)
s13_df$group2 <- gsub("\\(", "",s13_df$group2)
s13_df <- add_significance(s13_df,p.col = "p.value")

#add y_position
y_pos <-sqrt(max(ag_number_dend[,"Mito_per_Area_Dend"]))
s13_df$y_pos <- y_pos*1.05


p13 <- ggplot(ag_number_dend,aes(x = Condition, y = sqrt(Mito_per_Area_Dend))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s13_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  #geom_point(aes(color = Differentiation),alpha = 0.4,position=position_dodge(width=0.35)) +
  ylab("#Mitos per Area per Image\nDendrites (sqrt)") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  #coord_cartesian(ylim = c(0,7)) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/NumberMitos_Dend.png",p13, width = 6,height = 4.5, bg = "white")
```




#Axons
```{r}
ag_number_axon <- aggregate(Mito_Axon$Name_FileName,Mito_Axon[,c("Differentiation","Condition","CVS","Image")], FUN=length)
ag_number_axon <- merge(ag_number_axon,ImageMeans[,c("Differentiation","Condition","CVS","Image","Area_Axons")],by = c("Differentiation","Condition","CVS","Image"), all.x = TRUE)

ag_number_axon$Mito_per_Area_Axon <- ag_number_axon$x / ag_number_axon$Area_Axons
```


```{r}
ag_number_axon_stat <- aggregate(sqrt(ag_number_axon$Mito_per_Area_Axon),ag_number_axon[,c("Differentiation","Condition")], FUN=mean)

mod_s14<- rlm(x ~ Condition + Differentiation,data = ag_number_axon_stat)
s14 <- emmeans(mod_s14, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s14_df <- as.data.frame(s14$contrasts)
s14_df$group1 <- "pLNA-Ctrl"
s14_df$group2 <- s14_df$contrast
s14_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s14_df$group2)
s14_df$group2 <- gsub("\\(", "",s14_df$group2)
s14_df <- add_significance(s14_df,p.col = "p.value")

#add y_position
y_pos <-sqrt(max(ag_number_axon[,"Mito_per_Area_Axon"]))
s14_df$y_pos <- y_pos*1.05



p14 <- ggplot(ag_number_axon,aes(x = Condition, y = sqrt(Mito_per_Area_Axon))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s14_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("#Mitos per Area per Image\nAxon (sqrt)") +
  theme_classic()+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/NumberMitos_Axon.png",p14, width = 5.5,height = 4.5, bg = "white")
```




#Axons - Normalized
```{r}
ag_number_axon_norm <- aggregate(ag_number_axon$Mito_per_Area_Axon,ag_number_axon[,c("Differentiation","Condition")], FUN=mean)
ag_number_axon_norm$miR <- ag_number_axon_norm$Condition

ag_number_axon_norm_ctrl <- ag_number_axon_norm[ag_number_axon_norm$miR == "pLNA-Ctrl",]
colnames(ag_number_axon_norm_ctrl)[which(colnames(ag_number_axon_norm_ctrl) == "x")] <- "Ctrl_val"

ag_number_axon_norm <- merge(ag_number_axon_norm,ag_number_axon_norm_ctrl[,c("Differentiation","Ctrl_val")], by = c("Differentiation"), all.x = TRUE)
ag_number_axon_norm$Norm_val <- ag_number_axon_norm$x / ag_number_axon_norm$Ctrl_val
ag_number_axon_norm <- ag_number_axon_norm[ag_number_axon_norm$miR != "pLNA-Ctrl",]
```


```{r}
p15 <- ggplot(ag_number_axon_norm, aes(x = Condition, y = Norm_val)) +
  geom_bar(stat = "summary", fun = "mean", color = "darkgrey",
           fill = "white", linewidth = 1, show.legend = FALSE) +
  geom_point(aes(colour = Differentiation), 
             size = 2, show.legend = TRUE) +
  ylab("#Mitos per Area per Image\nAxon (sqrt) (Normalized to Ctrl.)") +
  geom_hline(yintercept = 1,linetype = "dashed") +
  theme_classic(base_size = 12)+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave2("../Figures/Processes/NumberMitos_Axon_Normalized.png",p15, width = 4,height = 4.5, bg = "white")
```












