---
title: "Untitled"
author: "Michael"
date: '2022-10-21'
output: html_document
editor_options: 
  chunk_output_type: inline
---



```{r}
suppressPackageStartupMessages({
  library(dplyr)
  library(ggplot2)
  library(ggsci)
  library(scales)
  library(emmeans)
  library(lmerTest)
  library(ggpubr)
  library(rstatix)
  library(ggsignif)
  library(cowplot)
  library(viridis)
  library(grid)
  library(gtable)
  library(lme4)
})
```




#Load Data
```{r}
e <- readRDS("../DataPrep/SomaMito.rds")
```



```{r}
#show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5])
```



##################
##################

#Entropy
```{r}
ag_ent <- aggregate(sqrt(e$Soma_Entropy),e[,c("Differentiation","Condition")], FUN=mean)
mod_s1 <- rlm(x ~ Condition + Differentiation,data = ag_ent) 
s1 <- emmeans(mod_s1, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- "pLNA-Ctrl"
s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s1_df$group2)
s1_df$group2 <- gsub("\\(", "",s1_df$group2)
s1_df <- add_significance(s1_df,p.col = "p.value")


#add y_position
y_pos <-sqrt(max(e[,"Soma_Entropy"]))
s1_df$y_pos <- y_pos*1.05


p1 <- ggplot(e,aes(x = Condition, y = sqrt(e$Soma_Entropy))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("Mitotracker Entropy in Soma (sqrt)") +
  theme_classic()+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))



ggsave2("../Figures/Soma/Soma_Entropy.png",p1, width = 5,height = 4.5, bg = "white")
```



#Intensity
```{r}
ag_int <- aggregate(sqrt(e$Intensity_MeanIntensity_Mitotracker_Soma),e[,c("Differentiation","Condition")], FUN=mean)
mod_s2 <- rlm(x ~ Condition + Differentiation,data = ag_int) 
s2 <- emmeans(mod_s2, trt.vs.ctrl ~ Condition , ref="pLNA-Ctrl")

s2_df <- as.data.frame(s2$contrasts)
s2_df$group1 <- "pLNA-Ctrl"
s2_df$group2 <- s2_df$contrast
s2_df$group2 <- gsub("\\) - \\(pLNA-Ctrl\\)","",s2_df$group2)
s2_df$group2 <- gsub("\\(", "",s2_df$group2)
s2_df <- add_significance(s2_df,p.col = "p.value")


#add y_position
y_pos <-sqrt(max(e[,"Intensity_MeanIntensity_Mitotracker_Soma"]))
s2_df$y_pos <- y_pos*1.05

p2 <- ggplot(e,aes(x = Condition, y = sqrt(Intensity_MeanIntensity_Mitotracker_Soma))) + 
  geom_violin(show.legend = FALSE) +
  stat_summary(
    fun = mean,
    geom="crossbar",
    show.legend = FALSE
  ) +
  stat_summary(aes(color = Differentiation),
    show.legend = TRUE,
    fun = mean,
    fun.max = function(x) {mean(x) + sd(x)},
    fun.min = function(x) {mean(x) - sd(x)},
    geom="pointrange", position=position_dodge(width=0.5), size = 0.75
  ) +
  ggsignif::geom_signif(
    data = s2_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  ylab("Mitotracker Intensity in Soma (sqrt)") +
  theme_classic()+
  scale_color_manual(values = col_vec) +
  theme(strip.text.x = element_text(size = rel(1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))



ggsave2("../Figures/Soma/Soma_Intensity.png",p2, width = 6,height = 4.5, bg = "white")
```

```{r}
legend <- get_legend(p1)

pp <- plot_grid(p1 + theme(legend.position="none"),
                NULL,
                p2 + theme(legend.position="none"),
                legend, rel_widths = c(1,0.1,1,0.6),nrow = 1)

ggsave2("../Figures/Soma/Soma_summary.png",pp, width = 8.5,height = 4.5, bg = "white")
```



