---
title: "Target_Comparison"
author: "Michael Soutschek"
date: "4 7 2023"
output: html_document
---




```{r}
library(SummarizedExperiment)
```



#load data
```{r}
#neurons
dea_plna <- read.csv("../../../pLNA_experiment/Target_Analysis/miR1229/target_data/dea1229_targets_genebased.csv")
Targets_plna <- dea_plna
Targets_plna <- dea_plna[!is.na(dea_plna$X8mer),]
Targets_plna <- Targets_plna[Targets_plna$X8mer > 0 | Targets_plna$X7mer > 0,]

Targets_plna <- Targets_plna[Targets_plna$logFC > 0,]
Targets_plna <- Targets_plna[Targets_plna$PValue < 0.05,]
```

#10nm

```{r}
#sy5y 10nm
dea_sy5y_10nm <- read.csv("../target_data/dea1229_targets_genebased_10nm.csv")
Targets_sy5y_10nm  <- dea_sy5y_10nm 
Targets_sy5y_10nm  <- Targets_sy5y_10nm[Targets_sy5y_10nm$X8mer  > 0 | Targets_sy5y_10nm$X7mer > 0,]
Targets_sy5y_10nm <- Targets_sy5y_10nm[!is.na(Targets_sy5y_10nm$gene_id),]

Targets_sy5y_10nm  <- Targets_sy5y_10nm[Targets_sy5y_10nm$logFC < 0,]
Targets_sy5y_10nm  <- Targets_sy5y_10nm[Targets_sy5y_10nm$PValue < 0.05,]
```



```{r}
#Comparison
Targets_10nm <- Targets_plna[Targets_plna$gene_name %in% Targets_sy5y_10nm$gene_name,]
write.csv(Targets_10nm,"../target_data/dea1229_targets_overlapwithpLNA_genebased_10nm.csv")
```


#20nm

```{r}
#sy5y 20nm
dea_sy5y_20nm <- read.csv("../target_data/dea1229_targets_genebased_20nm.csv")
Targets_sy5y_20nm  <- dea_sy5y_20nm 
Targets_sy5y_20nm  <- Targets_sy5y_20nm[Targets_sy5y_20nm$X8mer  > 0 | Targets_sy5y_20nm$X7mer > 0,]
Targets_sy5y_20nm <- Targets_sy5y_20nm[!is.na(Targets_sy5y_20nm$gene_id),]

Targets_sy5y_20nm  <- Targets_sy5y_20nm[Targets_sy5y_20nm$logFC < 0,]
Targets_sy5y_20nm  <- Targets_sy5y_20nm[Targets_sy5y_20nm$FDR < 0.05,]
```



```{r}
#Comparison
Targets_20nm <- Targets_plna[Targets_plna$gene_name %in% Targets_sy5y_20nm$gene_name,]
write.csv(Targets_20nm,"../target_data/dea1229_targets_overlapwithpLNA_genebased_20nm.csv")
```



#Combined

```{r}
#sy5y Combined
dea_sy5y_comb <- read.csv("../target_data/dea1229_targets_genebased_combined.csv")
Targets_sy5y_comb  <- dea_sy5y_comb 
Targets_sy5y_comb  <- Targets_sy5y_comb[Targets_sy5y_comb$X8mer  > 0 | Targets_sy5y_comb$X7mer > 0,]
Targets_sy5y_comb <- Targets_sy5y_comb[!is.na(Targets_sy5y_comb$gene_id),]

Targets_sy5y_comb  <- Targets_sy5y_comb[Targets_sy5y_comb$logFC < 0,]
Targets_sy5y_comb  <- Targets_sy5y_comb[Targets_sy5y_comb$PValue < 0.05,]
```



```{r}
#Comparison
Targets_comb <- Targets_plna[Targets_plna$gene_name %in% Targets_sy5y_comb$gene_name,]
write.csv(Targets_comb,"../target_data/dea1229_targets_overlapwithpLNA_genebased_combined.csv")
```








