---
title: "Pink1_HEK"
author: "Michael"
date: "2023-07-18"
output: html_document
---


```{r}
suppressPackageStartupMessages({
  library(tidyr)
  library(ggplot2)
  library(emmeans)
  library(readxl)
  library(scales)
  library(ggsci)
  library(ggplot2)
  library(MASS)
  library(emmeans)
  library(cowplot)
  library(rstatix)
  library(ggpattern)
  library(dplyr)
})
```

```{r}
show_col(pal_uchicago("default")(9))
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3],pal_uchicago("default")(9)[5],pal_uchicago("default")(9)[2])
```

#import data

```{r}
res <- read.csv("./synj2bp.csv")
```

```{r}
res_sum <- res %>%
  group_by(Mimic, Reporter, Replicate) %>%
  summarise(
    mean = mean(Fluc_Rluc_ratio)
  ) %>%
  ungroup()
```


#Format table

```{r}
res_sum$Mimic <- gsub("cntrl_mimic","Ctrl.",res_sum$Mimic)
res_sum$Mimic <- gsub("1229_mimic","miR-1229",res_sum$Mimic)
res_sum$Mimic <- factor(res_sum$Mimic,levels = c("Ctrl.","miR-1229"))

res_sum$Reporter <- gsub("SYNJ2BP_3'UTR","Synj2bp 3'UTR",res_sum$Reporter)
res_sum$Reporter <- gsub("Synj2bp 3'UTR_mut","Synj2bp 3'UTR mut.",res_sum$Reporter)
res_sum$Reporter <- factor(res_sum$Reporter,levels = c("Synj2bp 3'UTR","Synj2bp 3'UTR mut."))

res_sum$Replicate <- factor(res_sum$Replicate,levels = c("N1","N2","N3"))

res_sum$group <- paste0(res_sum$Reporter," _ ",res_sum$Mimic)
res_sum$group <- factor(res_sum$group,levels = c("Synj2bp 3'UTR _ Ctrl.","Synj2bp 3'UTR _ miR-1229","Synj2bp 3'UTR mut. _ Ctrl.","Synj2bp 3'UTR mut. _ miR-1229"))
```


#stats
```{r}
mod <- lm(mean ~ Mimic*Reporter + Replicate, data = res_sum)
s1 <- emmeans(mod,trt.vs.ctrl ~ Mimic|Reporter, ref = "Ctrl.")
```

```{r}
s1_df <- as.data.frame(s1$contrasts)
s1_df$group1 <- s1_df$contrast
s1_df$group1 <- gsub("\\(miR-1229\\) - ","",s1_df$group1)
s1_df$group1 <- paste0(s1_df$Reporter," _ ",s1_df$group1)

s1_df$group2 <- s1_df$contrast
s1_df$group2 <- gsub("\\) - Ctrl\\.","",s1_df$group2)
s1_df$group2 <- gsub("\\(", "",s1_df$group2)
s1_df$group2 <- paste0(s1_df$Reporter," _ ",s1_df$group2)

s1_df <- add_significance(s1_df,p.col = "p.value")


y_pos <- c()
for(i in levels(factor(res_sum$Reporter))) {
  ll <- max(res_sum[res_sum$Reporter == i,"mean"])
  y_pos <- c(y_pos,ll)
}


s1_df$y_pos <- y_pos + 0.2
s1_df$p.value.signif[s1_df$p.value.signif == "ns"] <- NA
```





#plot
```{r}
p1 <- ggplot(res_sum, aes(x = group, y = round(mean,3))) +
  geom_bar_pattern(aes(pattern = Mimic),
    position = position_dodge(preserve = "single"),
                   pattern_fill = "black",
                   pattern_angle = 45,
                   pattern_density = 0.1,
                   pattern_spacing = 0.025,
                   pattern_key_scale_factor = 0.6,
                   stat = "summary", fun = "mean",
                   fill = "white", color = "black") + 
   geom_point(aes(colour = Replicate),
             size = 2, show.legend = TRUE
             ) +
  ylab("Luminescence") +
  theme_classic(base_size = 12)+
  scale_colour_manual(values = col_vec) +
  scale_pattern_manual(values = c('miR-1229' = "none", 'Ctrl.' = "stripe")) +
  ggsignif::geom_signif(
    data = s1_df,
    aes(xmin = group1, xmax = group2, annotations = p.value.signif, y_position = y_pos),
    textsize = 4, vjust = -0.1, size = 0.75, manual = TRUE
  ) +
  scale_y_continuous(labels = scales::comma) + 
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 14), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        axis.title.y = element_text(size = rel(1.25))) +
  guides(pattern = guide_legend(override.aes = list(shape = NA))
         ) +
  #coord_cartesian(ylim = c(0,0.1)) +
  scale_x_discrete(labels=c("Synj2bp\n3'UTR","Synj2bp\n3'UTR","Synj2bp\n3'UTR\nmut.","Synj2bp\n3'UTR\nmut."))

ggsave2("./HEK_Synj2bp.png",p1, width = 5,height = 5, bg = "white")
```



