---
title: "longRNA DEA SE generation"
author: "tgermade"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: true
    toc_float: true
    theme: 'cerulean'
    highlight: 'tango'
    df_print: paged
---
  
  <style>
  .main-container {
    max-width: 1500px !important;
  }
</style>
  
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r libraries, warning=FALSE, message=FALSE}

suppressPackageStartupMessages({
  library(edgeR)
  library(SummarizedExperiment)
  library(SEtools)
})

source("../../../../Work/00_Scripts/dea.R")
source("../../../../Work/00_Scripts/roundSE.R")
```

## Allocation

```{r allocation}

# allocation

## filter: AT LEAST how many counts in AT LEAST how many samples? e.g. counts >= 10, samples >= 2
sel <- c(10, 2)
## input/output files
input <-"../../Salmon_Ens112/R/SE.salmon.raw_ens112.rds"
output <- "../data/SE.DEA.salmon.raw_ens112.rds"
output.no_round <- "../data/SE.DEA.noRound.salmon.raw_ens112.rds"
```

## Loading

```{r load se, warning=FALSE, message=FALSE}

# load raw SE file
se <- readRDS(input)
```

## Prep

```{r modify, message=FALSE, warning=FALSE, eval=TRUE}

# create batch variable
se$is.SC1 <- factor(se$diff=="SC1")
# filter raw data
se <- se[which(rowSums(assay(se) >= sel[1]) >= sel[2]),]
```

```{r add assays function, message=FALSE, warning=FALSE, eval=TRUE}

logAssays <- function(se, control,output){
  ## SE object with logCPM & logFC assays
  assays(se)$logcpm <- log1p(cpm(calcNormFactors(DGEList(assay(se)))))
  se <- SEtools::log2FC(se, controls = se$day==control, fromAssay = "logcpm", toAssay = output)
  return(se)
}
```

```{r add assays, message=FALSE, warning=FALSE, eval=TRUE}
se <- logAssays(se, 0, output = "log2FC.all")
se <- logAssays(se, 9, output = "log2FC.neur")
```

## PCA

```{r pca, message=FALSE, warning=FALSE, eval=TRUE}

# plot PCA to check for batch effect

## combined
# plgINS::plPCA(assays(se)$logcpm, as.data.frame(colData(se)), colorBy = "day", shapeBy = "diff",
#               add.labels = FALSE, annotation_columns = colnames(colData(se)))

```


## DEA over all stages

```{r dea all, message=FALSE, warning=FALSE, eval=TRUE}
# run DEA

se <- DEA(se, name = "all", model = ~is.SC1 + stage, model0 = ~is.SC1)
```

## DEA over neuronal stages

```{r dea neuronal, message=FALSE, warning=FALSE, eval=TRUE}
# run DEA

se <- DEA(se, use = which(se$day != "0"), name = "neuronal", model = ~is.SC1 + stage, model0 = ~is.SC1)
```



## Export

```{r add libsize info, eval=TRUE}
# add library size info to colData
se$libsize <- colSums(assay(se))
```

```{r export se no_round, eval=TRUE}
# export unrounded
saveRDS(se, output.no_round)
```

```{r export se round, message=FALSE, warning=FALSE, eval=TRUE}

# round
se <- roundSE(se)

# export rounded
saveRDS(se, output)
```




