---
title: "CaImaging"
author: "Michael"
date: '2022-10-17'
output: html_document
---


#libraries
```{r}
suppressPackageStartupMessages({
  library(data.table)
  library(ggplot2)
  library(stringr)
  library(reshape2)
  library(emmeans)
  library(ggrepel)
  library(emmeans)
  library(dplyr)
  library(cowplot)
  library(ggsci)
})
```



#get Data
```{r}
res <- readRDS("./CaImaging_Aggregated_Data.rds")
```

#colors
```{r}
col_vec <- c(pal_uchicago("default")(9)[1],pal_uchicago("default")(9)[3])
```





#Overview Amplitude Plot
```{r}
p1 <- ggplot(data = res, aes(x = Day, y  = log(Peak.Intensity.df.F.))) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(aes(color = Experiment), size = 1.5, alpha = 0.4) +
  geom_label(mapping=aes(x=Condition, y=-2.75, label= `#Cells_Day`)) + 
  annotate("text", label = "#Cells:", x = 0.5, y = -2.745) +
  coord_cartesian(xlim = c(0.75,6.25)) +
  ylab("Peak Intensitiy df/F (log)") +
  scale_color_manual(values = col_vec) + 
  theme_classic(base_size = 12) +
  xlab("") +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 16), 
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)),
        axis.text.y = element_text(size = rel(1)))


ggsave("../Figures/CaImaging_Timecourse_Amplitude_log.png",p1,width = 8,height = 5)
```


#Overview Frequency Plot
```{r}
p2 <- ggplot(data = res, aes(x = Day, y  = log(`Frequency [hz]`))) +
  geom_boxplot(outlier.shape = NA) +
  geom_point(aes(color = Experiment), size = 1.5, alpha = 0.4) +
  geom_label(mapping=aes(x=Condition, y=-6, label= `#Cells_Day`)) + 
  annotate("text", label = "#Cells:", x = 0.5, y = -6) +
  coord_cartesian(xlim = c(0.75,6.25)) +
  ylab("Frequency [hz] (log)") +
  scale_color_manual(values = col_vec) + 
  theme_classic() +
  xlab("") +
  theme(strip.text.x = element_text(size = rel(1.1)),
        strip.placement = "inside",
        text = element_text(size = 16),
        axis.title.x=element_blank(),
        axis.text.x = element_text(size = rel(1)))

ggsave("../Figures/CaImaging_Timecourse_Frequency_log.png",p2,width = 8,height = 5)
```

```{r}
pp1 <- plot_grid(p1,p2)
```









